{
  "hash": "8459d6e2c5a4d8f9b3832973d4ebaeb8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Outside Good Uncertainty\nsubtitle: Ordinal Dual Response in Choice-Based Conjoint Analysis\n\ndate: last-modified\nnumber-sections: true\n\naffiliations:\n  - id: nyu\n    name: New York University, Shanghai \n  - id: gbk\n    name: GBK Collective\n    \nauthor:\n  - name: Dan Yavorsky\n    orcid: 0000-0003-4095-6405\n    corresponding: true\n    email: dyavorsky@gmail.com\n    affiliations: \n      - ref: gbk\n  - name: Geoffery Zheng\n    orcid: 0000-0003-4229-8231\n    corresponding: false\n    email: gxz206@nyu.edu\n    affiliations: \n      - ref: nyu\n\nkeywords: choice-based conjoint analysis, dual response, stated preference elicitation, discrete choice methods, ordered choice, outside good\n\nabstract: |\n  We present a behavioral model in which consumers identify their most-preferred option among a set of alternatives but face uncertainty in their evaluation of the outside good. The model rationalizes the dual-response format used in choice-based conjoint analysis and extends the follow-up purchase question from binary to ordinal. The resulting likelihood function combines a multinomial logit for the forced choice with a cumulative-link ordinal model driven by the task's inclusive value. The link is logistic or Gumbel, depending on whether the respondent resolves her uncertainty before answering, and the binary dual-response model is a special case. We derive how much information a finer response scale adds, provide estimation routines for both aggregate and hierarchical Bayesian versions of the model, and show that the model outperforms both dichotomizing the scale into a binary response and assigning fixed purchase probabilities to each scale point. We apply the model to a choice-based conjoint study conducted in partnership with a consumer insights consultancy.\n  \nbibliography: references.bib\ncitation: true\n---\n\n\n<!-- Latex -->\n::: {.content-hidden unless-format=\"html\"}\n$$\n  \\newcommand{\\x}{\\mathbf{x}}\n  \\newcommand{\\bfbeta}{\\boldsymbol{\\beta}}\n  \\newcommand{\\betabar}{\\bar{\\bfbeta}}\n  \\newcommand{\\bftheta}{\\boldsymbol{\\theta}}\n  \\newcommand{\\iid}{\\stackrel{iid}{\\sim}}\n  \\newcommand{\\E}{\\operatorname{E}}\n  \\newcommand{\\coloneqq}{\\mathrel{:=}}\n$$\n:::\n\n::: {.content-hidden unless-format=\"pdf\"}\n```{=latex}\n  \\newcommand{\\x}{\\mathbf{x}}\n  \\newcommand{\\bfbeta}{\\boldsymbol{\\beta}}\n  \\newcommand{\\betabar}{\\bar{\\bfbeta}}\n  \\newcommand{\\bftheta}{\\boldsymbol{\\theta}}\n  \\newcommand{\\iid}{\\stackrel{iid}{\\sim}}\n  \\newcommand{\\E}{\\operatorname{E}}\n```\n:::\n\n\n\n<!-- Sections -->\n## Introduction {#sec-intro}\n\nConsumers are good at indicating which product they like best. They are often less certain about whether they would buy it. Choice-based conjoint analysis, the workhorse of stated-preference measurement in marketing [@Allenby_2019], has a device for separating these two: the dual-response format [@Brazell_2006]. In each task, the respondent first makes a forced choice among the displayed product profiles and then answers a follow-up question about whether she would actually purchase her selection. This format was introduced to address a practical problem with the traditional no-choice option: when \"none of these\" appears alongside the profiles in a traditional conjoint task, each time it is chosen contributes nothing to estimating attribute preferences. The dual-response design recovers that lost information because the forced choice always reveals preference among profiles, while still measuring demand for the category through the follow-up question, without systematically biasing the preference estimates [@Brazell_2006; @Dhar_2003]. Following its implementation in Sawtooth Software's widely used choice-based conjoint (CBC) system [@Diener_2006; @Sawtooth_2017], the dual-response format became a common practice in commercial conjoint research. However, the dual-response format was not derived from a behavioral model of the respondent, and any such model has to take a stand on what she is uncertain about when the follow-up question arrives. This paper supplies such a model for an ordinal follow-up. It rationalizes the dual-response format, determines the link function rather than assuming one, and extends the purchase question from binary to ordinal.\n\nWe start from the behavioral premise that a respondent facing a dual-response conjoint task can indicate her most-preferred product profile in the forced choice, but whether she would purchase her selection is a question pertaining to a hypothetical future occasion about which she remains genuinely uncertain. That second question has been canonically binary: \"would you buy the option you selected above?\", answered yes or no and modeled by pairing a multinomial logit for the forced choice with a binary logit for the purchase question [@Diener_2006; @Hung_2025_dual]. But a yes-or-no answer requires the respondent to settle something she has not yet had reason to settle. What she holds is a probability [@Manski_1990]. A finer scale would ask instead for her degree of conviction, and carry more information about what she will do. The natural extension is therefore an _ordinal_ dual-response follow-up, \"how likely are you to buy the option you selected above?\", answered, e.g., on a five-, seven-, or eleven-point scale from \"very unlikely\" to \"very likely.\" \n\nWe formalize that uncertainty as a component of utility for the outside good that she has not yet resolved, and, in our primary specification, we let the error components (for both the inside goods and the outside good) be independent Gumbel [@Mcfadden_1981; @Train_2009]. (Appendix D relaxes independence across goods to any generalized extreme value structure.) Together the behavioral premise and distributional kernel do two things for the model. First, they deliver a closed-form likelihood: the maximum of Gumbel utilities is itself Gumbel, with location equal to the log-sum inclusive value, and independent of which alternative attains it, so the two responses factor and the model pairs a multinomial logit for the forced choice with a cumulative link for the ordinal report. Second, they determine the link to be complementary log-log. The familiar ordered logit (logistic link) arises instead when the uncertainty is resolved before the follow-up, which is the assumption underlying the binary dual-response models and is stated explicitly by @Hung_2025_dual. At two scale points the logistic link is the \"Unified Model\" of @Hung_2025_dual, equivalently the DR-AnyMax model of @Diener_2006 and, once the inclusive value cancels, the single-stage multinomial logit with a no-choice constant [@Haaijer_2001]. Our model predicts a complementary log-log binary response, so the familiar yes/no follow-up is misspecified (if only mildly) whenever respondents remain uncertain.\n\nWe make four contributions. First, we develop the behavioral model: a utility-theoretic account of dual-response conjoint in which outside-good uncertainty is the primitive. That premise rationalizes the design and fixes the link function, and the cumulative-link family it generates contains the existing binary models as the two-point case of the alternative link, so the assumptions undelying those models become explicit and testable. Second, we analyze the information content of the ordinal follow-up: we derive the information a second response of a given length contributes and show that it is always non-negative and never falls when the scale is made finer, extending the binary efficiency results of @Brazell_2006 and @Hung_2025_dual and providing design guidance on how many scale points to use. Third, we provide estimation routines: maximum likelihood for the aggregate model and a custom Markov chain Monte Carlo sampler for the hierarchical Bayesian model with heterogeneous preferences, including an extension with respondent-specific cut points that accommodates individual differences in scale usage [@Greene_2010; @Falco_2015]. We also express the model in Apollo [@Hess_2019] both as a check on our implementation and as a route for readers already working in that framework. Fourth, we supply evidence, including simulation studies, that demonstrate parameter recovery and quantify the losses from dichotomization and constant-probability weighting, as well as an empirical application to a commercial choice-based conjoint study with an ordinal dual response, conducted in partnership with a consumer insights consultancy. Complete replication code accompanies the paper, with each study in the simulation program laid out as an executable notebook.\n\nSeveral literatures stand behind the model. Marketing work on dual-response and no-choice designs established why asking two questions beats a single question with \"none of these\" as an option: the preference information in a task survives even when the respondent would not buy. That work set the conventions for estimating such models [@Brazell_2006; @Diener_2006; @Haaijer_2001; @Hung_2025_dual], and the format itself is still being refined. For example, @Schlereth_2017 separate the forced and the free questions into blocks and add an adaptive rule for choosing which free questions to ask, which limits context effects and extreme response behavior when willingness to pay is the target. The appeal of the no-buy option has been demonstrated to shift as a respondent works through the choice tasks [@Hung_2025_nochoice]. The opt-out literature in choice modeling documents the consequences of getting the no-buy option wrong: misspecifying it degrades the accuracy of both willingness-to-pay estimates and market shares forecasts [@Campbell_2019].\n\nThe separation of the two decisions is older than the dual-response design. Demand models fit to supermarket scanner data have long estimated whether a household buys in a category separately from which brand it picks, joining the two stages through the inclusive value of the brand-choice stage [@Gupta_1988; @Bucklin_1992]. Our second response uses that device on survey data. Our statistical tools come from work on ordered and mixed response formats, from frameworks that handle ratings, rankings, and choices together [@Marshall_2002] to ordered-choice models that let different people use the same scale differently [@Greene_2010; @Falco_2015]. A further literature explains why the follow-up should ask for a probability. A yes/no question forces a rounding to zero or one, and @Manski_2004 argues that economists should elicit the probability itself. Marketing research made the same case decades earlier: @Juster_1966 replaced the yes/no buying-intentions question with an eleven-point probability scale, and @Morrison_1979 showed that stated intentions predict purchases only probabilistically, and that the mapping from one to the other depends on context. To our knowledge, no prior work derives the forced choice and the ordinal purchase answer from a single account of the consumer.\n\nThe remainder of the paper proceeds as follows. @sec-model develops the behavioral model, derives the joint likelihood, establishes the nesting relationships, and presents the information-content and estimation results. @sec-simstudy reports the simulation study. @sec-analysis presents the empirical application. @sec-discussion discusses implications for practice, including guidance on scale design, and @sec-conclusion concludes. Appendix A collects the proofs, Appendices B and C give the sampler and marginal-likelihood details, Appendix D extends the model to choice sets whose alternatives are correlated, and Appendix E gives the implementation in Apollo, a flexible R package for estimating choice models.\n\n\n\n## Model {#sec-model}\n\n### Setup\n\nConsumer $i=1,\\ldots,N$ faces choice tasks $t=1,\\ldots,T$. Each task presents a set of \"inside\" goods $\\mathcal{J}^{+} = \\lbrace 1,2,\\ldots,J \\rbrace$ alongside an \"outside\" good $j=0$, so that the full choice set is $\\mathcal{J} = \\lbrace 0,1,2,\\ldots,J \\rbrace$.[^tasksize] Consumer $i$ derives utility $u_{itj}$ from good $j$ in task $t$:\n$$\nu_{itj} = h(\\x_{tj}, \\bfbeta_i) + \\eta_{itj},\n$$ {#eq-utility}\nwhere $\\x_{tj}$ is a length-$P$ column vector of good characteristics, $\\bfbeta_i$ is a length-$P$ column vector of consumer-specific taste parameters, and $\\eta_{itj}$ encapsulates factors known to the consumer but unobserved by the researcher. We take $h(\\x_{tj}, \\bfbeta_i) = \\x_{tj}'\\bfbeta_i$ and write $V_{itj} \\coloneqq \\x_{tj}'\\bfbeta_i$ for this deterministic component, but the linear specification is not required.\n\n[^tasksize]: We hold $J$ fixed across tasks and consumers to lighten notation; nothing in what follows requires it.\n\nThe outside good is special in two respects. First, it is associated with a zero vector of characteristics ($\\x_{t0} = \\mathbf{0}$), so that $V_{it0}=0$; this is the standard normalization that anchors the location of utility [@Haaijer_2001]. Second, and this is the paper's central behavioral assumption, the consumer observes $\\eta_{itj}$ for all inside goods but does not observe $\\eta_{it0}$. She is comparing goods that are in front of her now; the outside good stands in for a purchase occasion that has not yet arrived, and her evaluation of it is uncertain.[^eta0motivation] [^eta0dist]\n\n[^eta0motivation]: This can be motivated by a framework in which $u_{it0} = 0$ and $u_{itj} = {\\x_{tj}}'\\bfbeta_i + \\eta_{itj} - \\eta_{it0}$ for $j \\in \\mathcal{J}^{+}$, where $\\eta_{it0}$ captures the consumer's uncertainty about her future tastes or circumstances at the moment of purchase. Because utilities are ordinal and $\\eta_{it0}$ is a common shock, it plays no role in the comparison among inside goods.\n\n[^eta0dist]: While the parametrization $\\eta_{it0} \\sim \\text{Gumbel}\\left(0,1\\right)$ preserves symmetry among the $J+1$ goods and is thus a natural choice, the framework easily accommodates alternative distributions for $\\eta_{it0}$. For example, an affine function of individual characteristics could accommodate individual-level variation in the propensity to prefer the outside good.\n\nIn each task the consumer provides two responses:\n\n1. **First response (choice).** She reports her preferred inside good,\n$$\nj^*_{it} = \\underset{j \\in \\mathcal{J}^+}{\\operatorname{arg max}} \\ u_{itj}.\n$$ {#eq-firstresponse}\nThis is a forced choice: the outside good is not among the options.\n\n2. **Second response (the ordinal report).** She reports a value $y_{it}$ on a discrete ordinal scale $w \\in \\mathcal{W} = \\lbrace 1, \\ldots, W \\rbrace$ (e.g., \"very unlikely\" to \"very likely\" on a five-point scale) that characterizes her evaluation of purchasing $j^*_{it}$, that is, of choosing it over the outside good. The binary dual-response format of @Brazell_2006 and @Diener_2006 is the special case $W=2$ of this design.\n\nWe model $\\eta_{itj} \\iid \\text{Gumbel} \\left( 0,1 \\right)$, independent of $\\x_{tj}$ and independent across goods, tasks, and consumers. This is the logit kernel standard in discrete choice [@Mcfadden_1981; @Train_2009], inherited by choice-based conjoint. The independence across goods is stronger than our derivation needs. Appendix D shows that @lem-gumbel holds for any generalized extreme value error structure once $S_{it}$ is replaced by the GEV generator, so the following results carry over to correlated alternatives, but for exposition we proceed with the independent errors assumption.\n\nTwo classical properties of the Gumbel family are used throughout [@Mcfadden_1981].\n\n::: {#lem-gumbel}\nLet $u_{itj} = V_{itj} + \\eta_{itj}$ with $\\eta_{itj} \\iid \\text{Gumbel}(0,1)$ for $j \\in \\mathcal{J}^+$, and define $u^*_{it} = \\max_{j \\in \\mathcal{J}^+} u_{itj}$. Then\n\n(i) $u^*_{it} \\sim \\text{Gumbel}\\left(\\overline{\\mu}_{it}, 1\\right)$ with location\n$$\n\\overline{\\mu}_{it} = \\ln S_{it},\n\\qquad\nS_{it} \\coloneqq \\sum_{j\\in\\mathcal{J}^{+}} \\exp \\left( V_{itj} \\right);\n$$ {#eq-max-mu}\n\n(ii) the identity of the maximizer $j^*_{it}$ and the value of the maximum $u^*_{it}$ are statistically independent.\n:::\n\nProperty (ii) makes the dual-response likelihood tractable: whatever the consumer tells us about the level of her best utility (the second response) is independent of which good delivered it (the first response), conditional on the deterministic utilities. Both properties are standard; Appendix A reproduces the short derivation.\n\n### First Response: Multinomial Logit\n\nThe first response is a standard forced choice among the inside goods. Under the Gumbel assumption,\n$$\n\\Pr \\left( j^*_{it} = j \\right)\n= \\frac{\\exp \\left( V_{itj} \\right)}{\\sum_{k\\in\\mathcal{J}^{+}} \\exp \\left( V_{itk} \\right)}\n= \\frac{\\exp \\left( V_{itj} \\right)}{S_{it}},\n$$ {#eq-mnl}\nthe multinomial logit over inside goods only. Note that the outside good does not appear: the forced choice does not depend on the consumer's uncertain evaluation of the outside good, which is the design's appeal [@Brazell_2006].\n\n### Second Response: An Ordinal Model of the Purchase Report\n\nWhat does the consumer consult when answering \"how likely are you to purchase the option you selected?\" Our premise answers the question: she has not resolved $\\eta_{it0}$, so what she has to report is a probability. That premise delivers a likelihood of *cumulative-link* form, depending on the choice set only through the inclusive value $\\overline{\\mu}_{it}$, and it determines the link. We derive that model first. We then ask what follows if she instead resolves the shock before answering, as @Hung_2025_dual assume. For a binary follow-up that assumption gives their Unified Model. Carried into an ordinal follow-up it is harder to interpret, for reasons we take up below.\n\n#### Reporting a Purchase Probability {#sec-modelA}\n\nThe consumer carries her uncertainty about the outside good into her answer and reports a probability. She knows $u^*_{it}$ (she just identified $j^*_{it}$) but does not know $\\eta_{it0}$, so from her perspective the probability that she would follow through and purchase $j^*_{it}$ is\n$$\np_{it} = \\Pr \\left( \\eta_{it0} < u^*_{it} \\mid u^*_{it} \\right) = F\\left( u^*_{it} \\right),\n$$ {#eq-purchprob}\nwhere $F(z) = \\exp(-e^{-z})$ is the standard Gumbel CDF. The ordinal scale discretizes the unit interval: fix cut points $0 = \\alpha_0 < \\alpha_1 < \\cdots < \\alpha_{W-1} < \\alpha_W = 1$ and suppose the consumer reports\n$$\ny_{it} = w\n\\quad \\Longleftrightarrow \\quad\np_{it} \\in \\left[ \\alpha_{w-1}, \\alpha_w \\right).\n$$ {#eq-reportruleA}\nWe assume consumers share the definitions of the qualitative scale labels, so the $\\alpha_w$ are common across consumers (we relax this in @sec-hetcut); the interior cut points are unobserved by the researcher and are estimated.\n\nReporting $y_{it}=w$ is equivalent to reporting that $u^*_{it} \\in \\left[ F^{-1}(\\alpha_{w-1}), \\, F^{-1}(\\alpha_w) \\right)$, an interval statement about the consumer's best utility. From the researcher's perspective, $u^*_{it} \\sim \\text{Gumbel}(\\overline{\\mu}_{it},1)$ by @lem-gumbel(i), so\n$$\n\\begin{aligned}\n\\Pr \\left( y_{it} = w \\right)\n&= F_{\\text{Gumbel}(\\overline{\\mu}_{it},1)} \\left( F^{-1}(\\alpha_w) \\right) - F_{\\text{Gumbel}(\\overline{\\mu}_{it},1)} \\left( F^{-1}(\\alpha_{w-1}) \\right) \\\\\n&= \\alpha_w^{\\,S_{it}} - \\alpha_{w-1}^{\\,S_{it}},\n\\end{aligned}\n$$ {#eq-modelA}\nTo see this, drop subscripts and note $F_{\\text{Gumbel}(\\overline{\\mu},1)}(z) = \\exp\\left( -e^{-(z - \\overline{\\mu})} \\right) = \\exp\\left( -e^{-z}S \\right) = \\left[ \\exp\\left( -e^{-z} \\right) \\right]^{S} = F(z)^{S}$ with $S = e^{\\overline{\\mu}}$. Evaluate that at $z = F^{-1}(\\alpha)$, where $F(z) = \\alpha$ by definition, and what is left is $\\alpha^{S}$. The second-response probabilities are differences of powers of the cut points, with the exponent $S_{it} = e^{\\overline{\\mu}_{it}}$ summarizing the attractiveness of the task's inside goods: the more attractive the set, the more probability mass shifts toward high scale points.[^beta] \n\nThe distribution's mean is $\\E \\left[ p_{it} \\right] = S_{it} \\big/ \\left( S_{it} + 1 \\right) = \\Lambda \\left( \\overline{\\mu}_{it} \\right)$: averaged over everything the researcher cannot see, the probability of purchase is the logistic of the inclusive value. Conditioning on what she reported rescales it. A consumer who answers $w$ has\n$$\n\\E \\left[ p_{it} \\mid y_{it} = w \\right] = \\frac{S_{it}}{S_{it}+1} \\cdot \\frac{\\alpha_w^{\\,S_{it}+1} - \\alpha_{w-1}^{\\,S_{it}+1}}{\\alpha_w^{\\,S_{it}} - \\alpha_{w-1}^{\\,S_{it}}},\n$$ {#eq-condexp}\nthe unconditional mean times a correction for the bin. Because $S_{it}$ appears here as well as in the bin boundaries, the same scale point implies different purchase probabilities in different tasks: what a label is worth depends on what was on the screen.\n\n[^beta]: Equivalently, from the researcher's perspective the consumer's purchase probability is Beta distributed, $p_{it} \\sim \\text{Beta}\\left(S_{it}, 1\\right)$. By the same power property, $\\Pr \\left( p_{it} \\le a \\right) = \\Pr \\left( u^*_{it} \\le F^{-1}(a) \\right) = a^{S_{it}}$, which is the $\\text{Beta}(S,1)$ distribution function on $[0,1]$. \n\n\n#### The Resolved Comparison, and the Binary Incumbent {#sec-modelB}\n\nSuppose instead that the consumer resolves the outside-good shock before answering and evaluates the realized utility difference\n$$\nd_{it} = u^*_{it} - \\eta_{it0}.\n$$\nThe binary question asks only for the sign of $d_{it}$, which is exactly what a consumer in this position can supply. Suppose she were also asked to grade its magnitude on a $W$-point scale. We know of no natural wording for that request: having resolved the comparison she has no likelihood left to report, and any graded answer would have to be read as an intensity rather than a probability. We carry the construction regardless, because at $W=2$ it reduces to the incumbent binary model. Formally, fix utility-scale cut points $-\\infty = c_0 < c_1 < \\cdots < c_{W-1} < c_W = \\infty$ and suppose\n$$\ny_{it} = w\n\\quad \\Longleftrightarrow \\quad\nd_{it} \\in \\left[ c_{w-1}, c_w \\right).\n$$ {#eq-reportruleB}\nFrom the researcher's perspective, $u^*_{it} \\sim \\text{Gumbel}(\\overline{\\mu}_{it},1)$ and $\\eta_{it0} \\sim \\text{Gumbel}(0,1)$ are independent, so their difference is logistic: $d_{it} \\sim \\text{Logistic}\\left( \\overline{\\mu}_{it}, 1 \\right)$. Hence\n$$\n\\Pr \\left( y_{it} = w \\right)\n= \\Lambda \\left( c_w - \\overline{\\mu}_{it} \\right) - \\Lambda \\left( c_{w-1} - \\overline{\\mu}_{it} \\right),\n\\qquad\n\\Lambda(z) = \\frac{1}{1+e^{-z}}.\n$$ {#eq-modelB}\nThis is an ordered logit [@Greene_2010] with the inclusive value $\\overline{\\mu}_{it}$ as the (negatively signed) linear predictor. The assumption that she resolves the shock before answering is what underlies the binary dual-response models. @Hung_2025_dual state it explicitly, specifying that respondents bring the same private information to both responses, and derive the binary case from it; @Diener_2006 reach the same functional form by a different route. It is not our model, but it is the specification the existing binary literature uses, and @sec-nesting shows why that use is well founded at $W=2$.\n\n\n#### A Common Form, and the Two Scales\n\nThe two accounts differ in where they place the thresholds, not in the shape of the model that results. @eq-reportruleA fixes them on the probability scale, where $\\alpha_w$ says directly what a scale label means; @eq-reportruleB fixes them on the utility scale, where $\\mathbf{c}$ sits alongside $\\overline{\\mu}_{it}$. They are the same thresholds in different units, related by $c_w = F^{-1}(\\alpha_w)$. Written on the utility scale, the second response is in both cases a cumulative link in the inclusive value,\n$$\n\\Pr \\left( y_{it} \\le w \\right) = F \\left( c_w - \\overline{\\mu}_{it} \\right),\n$$ {#eq-cumlink}\nthe complementary log-log link. Replacing $F$ with the logistic $\\Lambda$ gives @eq-modelB, which we invoke only at $W=2$, where it is the incumbent binary model (@sec-nesting).\n\nBoth scales are used below, and for a reason. We state the model in $\\boldsymbol{\\alpha}$, because those numbers say what a scale label is worth and are what an application reports. We work in $\\mathbf{c}$ wherever the argument concerns the location of $\\overline{\\mu}_{it}$: identification, the specification tests, the information results and estimation all sit on the utility scale, because a common shift in utilities is additive in $\\mathbf{c}$ and a power in $\\boldsymbol{\\alpha}$.\n\n\n### Joint Likelihood\n\nBy @lem-gumbel(ii), the value of $u^*_{it}$ is independent of the identity of $j^*_{it}$; and $\\eta_{it0}$ is independent of the inside-good components. The two responses in a task are therefore independent conditional on $(\\x_t, \\bfbeta_i)$, and the per-task likelihood contribution is simply the product of @eq-mnl and @eq-modelA:\n$$\nL_{it} \\left( \\bfbeta_i, \\boldsymbol{\\alpha} \\right)\n= \\underbrace{\\frac{\\exp \\left( V_{itj^*} \\right)}{S_{it}}}_{\\text{choice}}\n\\; \\times \\;\n\\underbrace{\\left( \\alpha_{y_{it}}^{\\,S_{it}} - \\alpha_{y_{it}-1}^{\\,S_{it}} \\right)}_{\\text{ordinal report}},\n$$ {#eq-joint}\nwith $\\boldsymbol{\\alpha} = (\\alpha_1, \\ldots, \\alpha_{W-1})$, and the respondent's likelihood $L_i = \\prod_{t} L_{it}$. This factorization is a consequence of @lem-gumbel(ii), the independence of the argmax and the maximum.\n\nThe per-task log-likelihood is therefore:\n$$\n\\ell_{it} = \\underbrace{V_{itj^*} - \\overline{\\mu}_{it}}_{\\text{choice}}\n\\; + \\;\n\\underbrace{\\ln \\left( \\alpha_{y_{it}}^{\\,S_{it}} - \\alpha_{y_{it}-1}^{\\,S_{it}} \\right)}_{\\text{ordinal report}},\n$$ {#eq-loglik}\nwith the sample log-likelihood $\\ell = \\sum_i \\sum_t \\ell_{it}$. The forced choice contributes the chosen good's utility measured against the inclusive value, so a task adds to the log-likelihood exactly to the extent that the chosen good stands out from the set. The ordinal report contributes the log of the $\\text{Beta}(S_{it},1)$ mass falling in the chosen bin, so it adds most when the attractiveness of the set sits in that bin. Specifically, a report near the top of the scale pulls $\\overline{\\mu}_{it}$ up, and a report near the bottom pulls it down. So in summary, the first term captures only how the goods compare with one another, while the second depends only only where they sit as a group.\n\n### The Model in Miniature {#sec-toy}\n\nBefore turning to special cases, we make the machinery concrete with the smallest interesting instance of the model: two respondents with identical preferences, one attribute, one task each, and a three-point scale. The example is deliberately tiny, but it exhibits the model's central mechanism.\n\nLet both respondents share the scalar taste parameter $\\beta = 1$, which we treat as known for the arithmetic. Each faces one task with two inside goods described by a single attribute $x$, answers the forced choice, and then reports on the three-point scale $\\mathcal{W} = \\lbrace \\text{\"unlikely\"}, \\text{\"unsure\"}, \\text{\"likely\"} \\rbrace$ with utility-scale cut points $\\mathbf{c} = (c_1, c_2) = (0, 2)$. (In our model these correspond to probability-scale cut points $\\left( \\alpha_1, \\alpha_2 \\right) = \\left( F(0), F(2) \\right) = (0.37, 0.87)$: the consumer answers \"unsure\" when her purchase probability lies between 37% and 87%.) The two tasks (one facing each respondent) are designed such that they differ only in the level of the attribute and not in its spread: consumer 1 faces an attractive pair, $x = (2, 1)$, and consumer 2 an unattractive pair, $x = (-1, -2)$.\n\nConsider the model's account of their behavior, giving both consumers the same realized components $\\eta = (0.30, -0.86)$ on their two inside goods. Consumer 1's utilities are $u = (2.30, 0.14)$: she picks her first good and knows her best utility, $u^* = 2.30$. She cannot resolve the outside-good shock $\\eta_0$, so she reports the bin containing her purchase probability $p = F(2.30) = 0.90$, namely \"likely.\" Consumer 2's utilities are $u = (-0.70, -2.86)$: she also picks her first good, but her best utility is $u^* = -0.70$, her purchase probability is $F(-0.70) = 0.13$, and she reports \"unlikely.\" The two consumers made identical first-response choices from identical realizations, yet gave opposite second responses.\n\nThe walkthrough above fixed one set of draws. Averaging over all of them, as the researcher must, we see that the pattern is not an accident of that particular draw (see @tbl-toy below). The forced-choice probabilities are the same function of the data for both consumers: the MNL depends only on the within-task difference $x_1 - x_2 = 1$, so $\\Pr(\\text{choose better good}) = \\Lambda(\\beta) = 0.73$ in both tasks. The forced choice reveals how much she prefers one option to the other, but nothing about how much she wants either. Instead, the tasks separate only through the inclusive value ($S_1 = e^2 + e^1 = 10.11$ versus $S_2 = e^{-1} + e^{-2} = 0.50$, i.e., $\\overline{\\mu}_1 = 2.31$ versus $\\overline{\\mu}_2 = -0.69$), which the cumulative-link stage compares against the cut points. (With $c_1 = 0$, consumer 2's probability of \"unlikely\" is $\\Lambda(-\\overline{\\mu}_2) = 1/(1+S_2) = 0.67$, the familiar no-choice probability of the single-stage MNL, which previews the nesting results below.)\n\n|  | Consumer 1 (attractive task) | Consumer 2 (unattractive task) |\n|---|:---:|:---:|\n| Attribute values $x$ | $(2,\\ 1)$ | $(-1,\\ -2)$ |\n| $\\Pr(\\text{choose better good})$ | $0.73$ | $0.73$ |\n| $S = \\sum_j e^{V_j}$, $\\ \\overline{\\mu} = \\ln S$ | $10.11$, $\\ 2.31$ | $0.50$, $\\ -0.69$ |\n| $\\Pr(y = w)$ | $(0.00,\\ 0.25,\\ 0.75)$ | $(0.60,\\ 0.33,\\ 0.07)$ |\n| $\\E \\left[ p \\mid y = \\text{\"unsure\"} \\right]$ | $0.80$ | $0.60$ |\n\n: Two tasks that are indistinguishable in the forced choice and nearly opposite in the ordinal report ($\\beta = 1$, $\\mathbf{c} = (0,2)$, $W = 3$). {#tbl-toy}\n\nThe joint likelihood of the observed data, in which each consumer chose her better good and $y_1 = \\text{\"likely\"}$, $y_2 = \\text{\"unlikely\"}$, follows from @eq-joint:\n$$\nL \\left( \\beta, \\alpha_1, \\alpha_2 \\right)\n= \\underbrace{\\Lambda(\\beta) \\Big[ 1 - \\alpha_2^{\\,S_1(\\beta)} \\Big]}_{\\text{consumer 1:} \\ \\ 0.73 \\times 0.75}\n\\times\n\\underbrace{\\Lambda(\\beta) \\, \\alpha_1^{\\,S_2(\\beta)}}_{\\text{consumer 2:} \\ \\ 0.73 \\times 0.60},\n$$ {#eq-toylik}\nwith $S_1(\\beta) = e^{\\beta} \\left( 1 + e^{\\beta} \\right)$ and $S_2(\\beta) = e^{-2\\beta} \\left( 1 + e^{\\beta} \\right)$. The example distills two general lessons.\n\nFirst, the two responses divide the labor of identification. The forced-choice factors involve only utility differences, and they identify $\\beta$ from within-task attribute variation. The ordinal factors involve utility levels, locating each task's $\\overline{\\mu}(\\beta)$ against the cut points. This is the division that @prp-ident formalizes. The forced choice identifies $\\beta$, as in any multinomial logit, because the two goods in a task differ in $x$. The ordinal responses then identify the cut points, by locating each task's $\\overline{\\mu}(\\beta)$ on the utility scale.\n\nSecond, the meaning of a scale label is set-dependent. The label \"unsure\" is fixed for the consumer, since by construction it means $p \\in [0.37, 0.87)$, but what the researcher should infer from it depends on the task: the expected purchase probability of a consumer who answers \"unsure\" is $0.80$ in the attractive task and $0.60$ in the unattractive one (@tbl-toy, last row), which is @eq-condexp evaluated at the two tasks.\n\n\n### Special Cases and Relation to Existing Models {#sec-nesting}\n\n**Binary dual response, logistic link.** Set $W=2$ with the single cut point $c_1 = \\gamma$. From @eq-modelB, $\\Pr(\\text{would buy}) = \\Lambda\\left( \\overline{\\mu}_{it} - \\gamma \\right) = S_{it} \\big/ \\left( e^{\\gamma} + S_{it} \\right)$, and the joint probabilities from @eq-joint reduce to:\n$$\n\\Pr \\left( j, \\text{buy} \\right) = \\frac{\\exp \\left( V_{itj} \\right)}{e^{\\gamma} + S_{it}},\n\\qquad\n\\Pr \\left( j, \\text{not buy} \\right) = \\frac{\\exp \\left( V_{itj} \\right)}{S_{it}} \\cdot \\frac{e^{\\gamma}}{e^{\\gamma} + S_{it}}.\n$$ {#eq-collapseB}\nWith $\\gamma = 0$ these are exactly the joint probabilities of the \"Unified Model\" of @Hung_2025_dual (their Eq. 4), which is in turn algebraically identical to the \"DR-AnyMax\" model of @Diener_2006; and @eq-collapseB with free $\\gamma$ is the standard single-stage MNL with a no-choice alternative-specific constant [@Haaijer_2001]. The cumulative-link framework of @eq-cumlink thus contains the leading binary dual-response model exactly, as its two-point case under the logistic link, and for $W>2$ the additional cut points are the only new parameters. \n\n**Binary dual response, our model.** Set $W=2$ in @eq-modelA: $\\Pr(\\text{not buy}) = \\alpha_1^{S_{it}} = F\\left( c_1 - \\overline{\\mu}_{it}\\right)$, a complementary log-log rather than logistic binary response. Our model therefore implies that even the familiar binary dual response is misspecified, if mildly given the proximity of the links, when consumers genuinely face outside-good uncertainty at the moment they answer. \n\n**DR-2Max.** The other binary model in the literature, \"DR-2Max\" [@Diener_2006], as implemented in Sawtooth Software's CBC/HB [@Sawtooth_2017], models the second response as a binary logit on the *chosen good's* deterministic utility: $\\Pr(\\text{buy} \\mid j^*) = e^{V_{itj^*}} \\big/ \\left( e^{V_{itj^*}} + e^{\\gamma} \\right)$. This requires drawing a fresh error for the chosen good in the second stage, so that the consumer who just declared $j^*$ best re-evaluates it from scratch. Under our framework such conditioning is unnecessary: by @lem-gumbel(ii) the distribution of the best utility does not depend on which good attained it, so the second response should depend on the set only through $\\overline{\\mu}_{it}$. \n\n**Reductions to the binary model.** An ordinal response can be reduced to a form the binary model accepts in two ways: (i) *dichotomization*, collapsing the scale at some point (e.g., top box or top two boxes) and estimating the binary model, which discards the ordinal information and hard-codes an arbitrary cut; or (ii) *constant-probability weighting*, mapping each scale point to a fixed purchase probability (e.g., \"definitely would buy\" $= 0.9$) independent of the choice set. These two reductions are the benchmarks in our simulation study (@sec-simstudy). Both are nested within, or dominated by, @eq-joint: dichotomization is @eq-collapseB applied to a coarsened $y_{it}$, and constant-probability weighting fixes the value of a scale point, which by @eq-condexp varies with the task through $S_{it}$. @sec-toy demonstrates the latter: the two consumers in the simple example are indistinguishable in the forced choice and both answer \"unsure,\" yet their expected purchase probabilities are $0.80$ in one task and $0.60$ in the other. No single value assigned to \"unsure\" can be right for both. \n\n### Identification {#sec-identification}\n\nBecause the second response depends on the choice set only through the log-sum $\\overline{\\mu}_{it}$, and because the cut points sit on the same utility scale as $\\overline{\\mu}_{it}$, the model requires a location normalization. This subsection makes the requirement precise. Fix the aggregate model ($\\bfbeta_i = \\bfbeta$) and let a task $t$ have inside-good attribute vectors $\\lbrace \\x_{tj} \\rbrace_{j \\in \\mathcal{J}^+}$ and responses $\\left( j^*_t, y_t \\right)$ generated by @eq-joint with parameter $\\theta = \\left( \\bfbeta, \\mathbf{c} \\right) \\in \\mathbb{R}^P \\times \\mathcal{C}$, where $\\mathcal{C} = \\lbrace \\mathbf{c} : c_1 < \\cdots < c_{W-1} \\rbrace$. Call $\\theta$ and $\\theta'$ *observationally equivalent* if they imply the same joint probabilities $\\Pr_\\theta \\left( j^*_t = j, y_t = w \\right)$ for every task design in the support of the design distribution, and let $X$ denote the design matrix that stacks the rows $\\x_{tj}'$ over all inside goods and tasks in that support.\n\n::: {#prp-ident}\n$\\theta = \\left( \\bfbeta, \\mathbf{c} \\right)$ is identified if and only if the augmented matrix $\\left[ X \\;\\; \\iota \\right]$ has full column rank $P+1$, where $\\iota$ is a conformable vector of ones. Equivalently: the only $\\left( v, \\delta \\right) \\in \\mathbb{R}^P \\times \\mathbb{R}$ satisfying $\\x_{tj}'v = \\delta$ for every inside good $j$ and task $t$ is $\\left( v, \\delta \\right) = \\left( \\mathbf{0}, 0 \\right)$.\n:::\n\n::: {.proof}\n(*Sufficiency.*) Suppose $\\theta$ and $\\theta' = \\left( \\bfbeta', \\mathbf{c}' \\right)$ are observationally equivalent. Marginalizing the joint probabilities over $y$ equates the MNL choice probabilities task by task, which implies $\\left( \\x_{tj} - \\x_{tk} \\right)' \\left( \\bfbeta - \\bfbeta' \\right) = 0$ for all $j,k,t$; hence $\\x_{tj}' \\left( \\bfbeta - \\bfbeta' \\right) = a_t$, a constant within each task. Marginalizing over $j$ equates the cumulative ordinal probabilities: $F \\left( c_w - \\overline{\\mu}_t(\\bfbeta) \\right) = F \\left( c'_w - \\overline{\\mu}_t(\\bfbeta') \\right)$ for all $w,t$. Since $F$ is strictly increasing, $c_w - c'_w = \\overline{\\mu}_t(\\bfbeta) - \\overline{\\mu}_t(\\bfbeta')$ for all $w,t$; the left side is free of $t$ and the right side free of $w$, so both equal a constant $\\delta$. Direct computation gives $\\overline{\\mu}_t(\\bfbeta') = \\ln \\sum_j \\exp \\left( V_{tj} - a_t \\right) = \\overline{\\mu}_t(\\bfbeta) - a_t$, so $a_t = \\delta$ for every $t$; that is, $\\x_{tj}' \\left( \\bfbeta - \\bfbeta' \\right) = \\delta$ for all $j,t$. The rank condition then forces $\\bfbeta = \\bfbeta'$ and $\\delta = 0$, hence $\\mathbf{c} = \\mathbf{c}'$. (*Necessity.*) If some $\\left( v, \\delta \\right) \\ne \\left( \\mathbf{0}, 0 \\right)$ satisfies $\\x_{tj}'v = \\delta$ everywhere, then $\\theta' = \\left( \\bfbeta + v, \\mathbf{c} + \\delta \\iota \\right)$ shifts every $V_{tj}$ and every cut point by $\\delta$, leaving the MNL probabilities (a within-task constant drops out) and the ordinal probabilities ($F(c_w + \\delta - (\\overline{\\mu}_t + \\delta))$) unchanged, so $\\theta' \\ne \\theta$ is observationally equivalent to $\\theta$. $\\square$\n:::\n\n**The condition in miniature.** Return to the two consumers of @sec-toy, with $\\beta = 1$ and $\\mathbf{c} = (0,2)$, so that $\\overline{\\mu}_1 = 2.31$ and $\\overline{\\mu}_2 = -0.69$. Suppose the design had carried a constant: one extra attribute, equal to one for every good, with part-worth $\\beta_{\\text{const}}$. Setting $\\beta_{\\text{const}} = 1$ raises every $V_{tj}$ by one and therefore raises both inclusive values by exactly one, to $3.31$ and $0.31$. Raise both cut points by one as well, to $\\mathbf{c} = (1,3)$, and every difference $c_w - \\overline{\\mu}_t$ returns to the value it had: $(-2.31, -0.31)$ for the first consumer and $(0.69, 2.69)$ for the second. The two ordinal distributions are therefore exactly what they were. The forced choice never saw the constant at all, since it turns on $\\x_{t1} - \\x_{t2}$. No quantity of data separates $\\left( \\beta_{\\text{const}}, \\mathbf{c} \\right) = \\left( 0, (0,2) \\right)$ from $\\left( 1, (1,3) \\right)$, or from any other point along that ridge, and it is the cut points rather than the part-worths that do the absorbing.\n\nSeveral remarks unpack the content of @prp-ident.\n\n**What the condition rules out.** A violating direction $\\left( v, \\delta \\right)$ is an attribute combination whose value is the same for every inside good ever shown. The leading case is an intercept: a column of ones in $X$ makes $\\left[ X \\;\\; \\iota \\right]$ rank deficient by construction. The subtler case is a *hidden* intercept: if an attribute is dummy-coded with all $L$ of its levels included, every alternative carries exactly one of them, so the dummies sum to $\\iota$ and the same invariance appears (shift all $L$ part-worths and all cut points equally). Attributes must therefore be coded against omitted reference levels (or effects-coded), and the design must contain no global constant. This requirement is stricter than in the single-stage MNL with a no-choice alternative, where a full set of brand dummies is identified because the no-choice row of zeros breaks the constancy [@Haaijer_2001]. In the dual-response model the outside good never appears as a design row, since its role is absorbed by the cut points, so anything the design holds constant across inside goods is absorbed along with it.\n\n**What the normalizations do.** The convention $\\x_{t0} = \\mathbf{0}$ with a $\\text{Gumbel}(0,1)$ shock fixes the origin against which the cut points are measured: an outside-good alternative-specific constant would shift all cut points equally and is exactly the invariance in the proof, so it is subsumed rather than restricted. (Its visible trace is the binary case: at $W=2$, the logistic link's single cut point $c_1$ *is* the no-choice constant of @eq-collapseB.) The unit Gumbel scale fixes the scale of $\\bfbeta$, as in any logit. Beyond these, the model imposes a genuine restriction rather than a normalization: the coefficient on $\\overline{\\mu}_{it}$ in @eq-cumlink is fixed at $1$ by the theory, because both responses are driven by the same utility draw, so estimating a free slope $\\lambda$ on $\\overline{\\mu}_{it}$ and testing $\\lambda = 1$ is an overidentification test of the behavioral model, not a required normalization.\n\n**Cut points versus the link.** Given $\\bfbeta$ (identified from the forced choice alone whenever $X$'s within-task differences have full rank), the cut points are exactly identified even *without* variation in task attractiveness: $c_w = \\overline{\\mu} + G^{-1} \\left( \\Pr(y \\le w) \\right)$ pointwise. Variation in $\\overline{\\mu}_{it}$ across tasks therefore overidentifies $\\mathbf{c}$, and it is what identifies the link: at a single value of $\\overline{\\mu}$, any two strictly increasing links fit the $W$ category frequencies perfectly by relabeling cut points, so the shape of the link is identified only through how the ordinal distribution shifts as $S_{it}$ varies. Designs that hold task attractiveness fixed cannot speak to it at all.\n\n**Population versus sample.** Under @prp-ident every scale category has strictly positive probability in every task ($G$ is strictly increasing on $\\mathbb{R}$ and the cut points are finite), so no support condition is needed for point identification. In finite samples, however, rarely used categories leave their adjacent cut points weakly identified, and near-violations of the rank condition (attribute combinations *nearly* constant across inside goods) manifest as an ill-conditioned information matrix. Both pathologies are visible in the smallest eigenvalues of the observed information, a diagnostic we report alongside the simulation results in @sec-simstudy.\n\n**Numerical verification.** We verify @prp-ident computationally (replication code accompanies the paper). Data simulated from the raw behavioral process (Gumbel utility draws, argmax, and the two reporting rules, not the derived likelihood) at three distinct parameter configurations for each model, on designs satisfying the rank condition, are recovered by maximum likelihood: across all configurations the true parameter vector lies inside the 95% likelihood-ratio confidence region, the observed information is well-conditioned, repeated-sampling bias is statistically indistinguishable from zero, and model-based standard errors match the empirical sampling variation. Appending an intercept column, the canonical violation, produces exactly the predicted failure: $\\left[ X \\;\\; \\iota \\right]$ loses rank, the smallest eigenvalue of the observed information collapses to zero, and different starting values converge to different raw $\\left( \\beta_{\\text{const}}, \\mathbf{c} \\right)$ on the flat ridge while agreeing, to numerical precision, on the identified combinations $c_w - \\beta_{\\text{const}}$ and the non-constant coordinates of $\\bfbeta$. The same exercise confirms the factorization in @eq-joint: the empirical joint distribution of $\\left( j^*, y \\right)$ from one million behavioral draws is statistically indistinguishable from the product form.\n\n### Specification Tests {#sec-spectests}\n\nBecause the theory restricts more than it parameterizes, the model is overidentified in two directions that convert directly into one-degree-of-freedom specification tests. Both are computed from the aggregate likelihood at trivial cost, and both have well-behaved operating characteristics (@sec-simstudy).\n\n**The unit-slope test.** The behavioral model fixes the coefficient on the inclusive value in the second stage at exactly one, because the same utility draw generates both responses, so the natural one-parameter enlargement\n$$\n\\Pr \\left( y_{it} \\le w \\right) = F \\left( c_w - \\lambda \\, \\overline{\\mu}_{it} \\right)\n$$ {#eq-lambda}\nnests the model at $\\lambda = 1$. A free $\\lambda$ is identified by how the ordinal response distribution shifts as task attractiveness varies (@sec-identification), and departures are interpretable: $\\lambda < 1$ indicates the second response under-reacts to the quality of the displayed set (consistent with inattention to the set or with scale-use compression), while $\\lambda > 1$ indicates over-reaction. Testing $H_0\\!: \\lambda = 1$ by likelihood ratio or Wald is an overidentification test of the joint utility account, not a normalization check.\n\n**The conditioning test.** The framework implies the second response depends on the choice set only through $\\overline{\\mu}_{it}$ (@lem-gumbel), whereas the DR-2Max tradition conditions on the chosen alternative's utility. The enlargement\n$$\n\\Pr \\left( y_{it} \\le w \\right) = F \\left( c_w - \\left[ \\overline{\\mu}_{it} + \\delta \\left( V_{itj^*} - \\overline{\\mu}_{it} \\right) \\right] \\right)\n$$ {#eq-delta}\nspans the two: $\\delta = 0$ is our model and $\\delta = 1$ puts the full weight on the chosen option's deterministic utility, the DR-2Max predictor. Both points are testable against the estimated $\\delta$, so the long-standing 2Max-versus-AnyMax question [@Diener_2006; @Hung_2025_dual] becomes a parameter estimate rather than a model-selection exercise.\n\nWe apply both tests to the empirical data in @sec-analysis. Their finite-sample size and power, including full power of the $\\delta$ test against DR-2Max data at modest sample sizes, are documented in the simulation study.\n\n### The Information Content of the Ordinal Response {#sec-information}\n\nHow much does a $W$-point second response add over a binary one? The question has a clean answer in terms of Fisher information, extending the efficiency analysis of @Hung_2025_dual from binary to ordinal second responses.\n\nThe per-task Fisher information about $\\bfbeta$ decomposes into the familiar MNL term [@Huber_1996] plus a second-response increment. Writing $\\pi_w = F(c_w - \\overline{\\mu}) - F(c_{w-1} - \\overline{\\mu})$ and $f = F'$, the second response contributes\n$$\n\\mathcal{I}^{(2)}_{it}\n= \\omega \\left( \\overline{\\mu}_{it}; \\mathbf{c} \\right) \\, \\overline{\\x}_{it} \\, \\overline{\\x}_{it}',\n\\qquad\n\\omega = \\sum_{w=1}^{W} \\frac{ \\left[ f \\left( c_w - \\overline{\\mu} \\right) - f \\left( c_{w-1} - \\overline{\\mu} \\right) \\right]^2 }{ \\pi_w },\n$$ {#eq-fisher}\nwhere $\\overline{\\x}_{it} = \\sum_{j \\in \\mathcal{J}^+} \\Pr\\left(j^*_{it}=j\\right) \\x_{tj}$ is the choice-probability-weighted average attribute vector (the gradient of $\\overline{\\mu}_{it}$ with respect to $\\bfbeta$). Two properties follow. First, the increment is positive semi-definite: the second response never destroys information, as in the binary result of @Hung_2025_dual. Second, $\\omega$ is non-decreasing under refinement of the scale partition, since coarsening an ordinal response is a garbling in the sense of sufficiency. The binary response ($W=2$) is therefore the least informative member of the family, and information rises toward the continuous-report limit as $W \\to \\infty$. @sec-simstudy quantifies the practical magnitudes: how much of the binary-to-continuous gap a five- or seven-point scale captures, and how the gains vary with task attractiveness.\n\n<!-- TODO: verify placement — full derivation of @eq-fisher and the refinement argument in an appendix. -->\n\n### Heterogeneity {#sec-heterogeneity}\n\nWe accommodate preference heterogeneity with a standard hierarchical Bayesian specification [@Rossi_2005; @Train_2001]:\n$$\n\\bfbeta_i \\iid \\mathcal{N} \\left( \\betabar, \\Sigma_{\\beta} \\right),\n$$ {#eq-hb}\nwith conjugate priors on $\\left( \\betabar, \\Sigma_{\\beta} \\right)$. In the main model the cut points $\\mathbf{c}$ are common across consumers: the scale labels (\"very likely,\" \"somewhat likely,\" ...) are assumed to mean the same thing to everyone, while preferences vary.\n\n#### Heterogeneous Cut Points {#sec-hetcut}\n\nThe assumption of a shared reporting scale is convenient but contestable: @Greene_2010 and @Falco_2015 document individual differences in the use of ordinal response scales. We therefore develop an extension with consumer-specific cut points. Parameterize\n$$\nc_{i1} \\in \\mathbb{R},\n\\qquad\nc_{iw} = c_{i,w-1} + \\exp \\left( \\delta_{iw} \\right) \\ \\text{for} \\ w = 2, \\ldots, W-1,\n$$ {#eq-hetcutparam}\nand let $\\bftheta_i = \\left( c_{i1}, \\delta_{i2}, \\ldots, \\delta_{i,W-1} \\right)'$ follow a multivariate normal population distribution, estimated jointly with (and, if desired, correlated with) $\\bfbeta_i$. The exponentiated increments enforce monotonicity without constrained sampling. Identification at the individual level is necessarily partial, because with $T$ tasks per consumer the $W-1$ individual cut points and $P$ individual preference parameters are jointly informed by only $T$ ordinal reports. The hierarchy therefore matters here since it shrinks each respondent's scale usage toward a population distribution that is estimated from the whole sample. @sec-simstudy examines both the payoff to permitting cut-point heterogeneity when it is present in the data-generating process and the robustness of the common-cut-point model when it is not.\n\n**Identification with heterogeneity.** @prp-ident applies respondent by respondent once $\\bfbeta_i$ varies: individual-level identification requires the rank condition on each respondent's own stacked design (their $T \\times J$ rows), which rotating commercial designs typically satisfy. The hierarchy then supplies shrinkage, not identification of the model's fixed features. In the heterogeneous-cut-point extension above, the same location tension reappears at the individual level, where a respondent-specific utility shift trades off against $c_{i1}$ within that respondent's likelihood, and is resolved by the same condition applied to the individual design, with the hierarchical prior doing real work when $T$ is small.\n\n### Estimation {#sec-estimation}\n\nThe aggregate (homogeneous-$\\bfbeta$) model is estimated by maximum likelihood: the log of @eq-joint summed over consumers and tasks is smooth in $\\left( \\bfbeta, \\mathbf{c} \\right)$ after the monotonicity-preserving reparameterization of the cut points, and standard quasi-Newton methods converge quickly. One term needs care. When a scale point is rarely used, the two powers in @eq-loglik differ only in a late decimal place, and subtracting them as written would discard most of the precision the computer has; the code evaluates an algebraically identical rearrangement that never forms that difference (Appendix B). Because the likelihood is a product of a choice component and an ordinal component, it can also be assembled in Apollo [@Hess_2019] from that package's standard building blocks, which we do as an independent check on our own code. Appendix E gives the details.\n\nThe hierarchical model is estimated with a custom Markov chain Monte Carlo sampler, implemented in R and following the hybrid Gibbs architecture of @Rossi_2005: (1) a random-walk Metropolis step for each $\\bfbeta_i$ (and $\\bftheta_i$ in the heterogeneous-cut-point extension) using the individual likelihood $\\prod_t L_{it}$; (2) a random-walk Metropolis step for the common cut-point block on the unconstrained scale; and (3) conjugate draws for the population moments $\\left( \\betabar, \\Sigma_{\\beta} \\right)$. Model comparison uses the log marginal density approximated by the method of @Newton_1994, matching the practice in @Hung_2025_dual and permitting direct comparisons among our model, the binary dual-response models, and the practitioner heuristics. Complete replication code accompanies the paper. \n\n\n## Simulation Study {#sec-simstudy}\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nrd <- function(f) readRDS(file.path(\"R\", \"output\", f))\nidt <- rd(\"aggregate_recovery.rds\")\nrep_study <- rd(\"replication_study.rds\")\ndich <- rd(\"dichotomization_study.rds\")\nspec <- rd(\"spec_tests.rds\")\ndg <- rd(\"design_guidance.rds\")\nhbv <- rd(\"hb_validation.rds\")\nhbcov <- rd(\"hb_coverage.rds\")\nhb_dich <- rd(\"hb_simstudy_dichot.rds\")\nhb_wl <- rd(\"hb_simstudy_wronglink.rds\")\nhb_hc <- rd(\"hb_simstudy_hetcut.rds\")\nhb_ng <- rd(\"hb_simstudy_nongumbel.rds\")\nhb_ne <- rd(\"hb_simstudy_nested.rds\")\nhb_dr <- rd(\"hb_simstudy_drift.rds\")\ncf <- rd(\"counterfactual.rds\")\npct <- function(x, d = 0) sprintf(paste0(\"%.\", d, \"f%%\"), 100 * x)\nr2 <- function(x, d = 2) sprintf(paste0(\"%.\", d, \"f\"), x)\n```\n:::\n\n\nThe simulation program serves six purposes: verify that the estimators recover the model's parameters and that the identification theory of @sec-identification bites where it says it does; quantify what dichotomization costs, in the aggregate and, where it matters more, at the individual level; establish the operating characteristics of the specification tests of @sec-spectests; probe robustness to the misspecifications a referee should worry about; turn the information results of @sec-information into design guidance; and attach economic stakes to the choice of estimator through a pricing counterfactual.\n\nTwo conventions apply throughout. All data are simulated from the *behavioral process*, meaning raw Gumbel utility draws, the argmax, and the reporting rules, never from the derived likelihood, so parameter recovery validates the derivation and the code at the same time. And every experiment is seeded and reproducible.\n\nEach subsection below summarizes one study and points to the notebook that contains it. The notebooks accompany the paper, run the experiments end to end, and are the source of the numbers reported here; they also carry the diagnostics, intermediate tables, and negative controls that are not worth article space. Readers who want to see a result rather than take it on trust should start there.\n\n### Design {#sec-simdesign}\n\nThe aggregate experiments use pooled tasks with $J = 4$ alternatives described by two 3-level attributes (dummy-coded against reference levels) and a continuous price-like attribute ($P = 5$), a $W = 5$ scale, across four parameter configurations that vary the location and spread of the response distribution. One is a *skewed* configuration with realistic bottom-heavy purchase intent (top-2-box share 18.4%), which is where the top-2-box convention is worst placed. The hierarchical experiments use $N = 300$ respondents, $T = 12$ estimation tasks plus 2 holdouts, $\\bfbeta_i \\sim \\mathcal{N}(\\betabar, \\Sigma)$ with substantial heterogeneity, and the same attribute scheme.\n\n### Parameter Recovery and Identification {#sec-sim-agg}\n\n**Aggregate.** [Notebook 2](notebooks/02-aggregate-recovery.qmd) runs three parameter configurations per link at 20,000 tasks each. In every case the true parameter vector lies inside the 95% likelihood-ratio confidence region, the observed information is strongly positive definite, and the probability-scale cut points of our model recover to within a percentage point: a true $\\alpha_1 = 0.02$ in the stress configuration is estimated at 0.0196. Repeated-sampling behavior matches the asymptotics. Across 40 independent datasets per link at $n = 5{,}000$, no parameter shows significant bias (max $|t| = 2.05$ over 18 tests) and model-based standard errors match the empirical sampling variation (mean calibration ratio 1.008). Quadrupling $n$ shrinks the largest observed bias in proportion, as $O(1/n)$ requires, which is what distinguishes ordinary finite-sample bias from a structural problem.\n\nThe same notebook carries two checks the analysis of @sec-identification already anticipates, and which are therefore reported there rather than here. Appending an intercept, the canonical violation of @prp-ident, collapses the smallest eigenvalue of the observed information and produces the predicted flat ridge: different starting values reach identical likelihoods at different raw $(\\beta_{\\text{const}}, \\mathbf{c})$ while agreeing to four decimal places on the identified combinations. And the empirical joint distribution of the two responses over one million behavioral draws is statistically indistinguishable from the product form of @eq-joint, confirming the factorization that makes the likelihood tractable.\n\n**Hierarchical.** [Notebook 3](notebooks/03-hierarchical-recovery.qmd) establishes that the sampler of @sec-estimation recovers population means, covariances, and cut points on synthetic panels, and that its posterior uncertainty is calibrated: across 8 replications, 90% central posterior intervals cover the truth at 89% and 83% respectively, with 50% intervals at 51% and 43%. Calibration matters independently of recovery, since a sampler can find the right answer and still misstate its own uncertainty. As an independent check of the hierarchy machinery, the forced-choice-only special case of our sampler agrees with an established hierarchical-MNL implementation on identical data to within 0.007 on every population parameter.\n\n### The Cost of Dichotomization {#sec-sim-benchmarks}\n\nCollapsing the $W$-point response at a cut point yields a correctly specified binary dual-response model, so dichotomization costs efficiency and never consistency; [notebook 4](notebooks/04-dichotomization-cost.qmd) confirms this with bias tests in every cell. The comparison is therefore about precision, and it is computed two ways: exactly, from the Fisher information, and by paired Monte Carlo, fitting the ordinal model and the binary model to the *same* simulated datasets so that all differences are attributable to the coarsened second response.\n\n**Aggregate: modest at a lucky cut, material at an unlucky one.** @tbl-dichot reports exact variance ratios, equivalently the extra sample the binary analyst needs, for the top-2-box convention and for the worst fixed cut. Top-2-box dichotomization costs 4%–15% extra sample for the preference parameters while discarding 27%–52% of the second response's own information; the worst cuts cost up to 33%. The analyst must commit to the cut before seeing the data, so the worst case is the relevant risk. The ordinal model is uniformly within about 2% of the full-information benchmark. Aggregate demand-*prediction* ratios are small (1.01–1.07) because prediction variance is dominated by the forced-choice stage that both estimators share, an honest caveat that the individual-level results overturn.\n\n\n::: {#tbl-dichot .cell tbl-cap='Exact asymptotic variance ratios versus the full 5-point model (extra sample required for equal precision), and the share of the second response\\'s information each coarsening retains. Top-2-box = the literature\\'s default dichotomization. Full study in notebook 4.'}\n\n```{.r .cell-code .hidden}\ntab <- do.call(rbind, lapply(names(dich$analytic), function(sn) {\n  a <- dich$analytic[[sn]]$sd\n  data.frame(configuration = sn,\n             `top-2-box, beta` = round((a$mean_sd_beta[5] / a$mean_sd_beta[1])^2, 3),\n             `worst cut, beta` = round(max((a$mean_sd_beta / a$mean_sd_beta[1])^2, na.rm = TRUE), 3),\n             `omega share, top-2-box` = round(a$mean_omega[5] / a$mean_omega[1], 2),\n             `omega share, worst` = round(min(a$mean_omega[-1] / a$mean_omega[1], na.rm = TRUE), 2),\n             check.names = FALSE)\n}))\nknitr::kable(tab, row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|configuration | top-2-box, beta| worst cut, beta| omega share, top-2-box| omega share, worst|\n|:-------------|---------------:|---------------:|----------------------:|------------------:|\n|set1_moderate |           1.041|           1.091|                   0.73|               0.38|\n|set2_negative |           1.088|           1.119|                   0.59|               0.40|\n|set3_stress   |           1.152|           1.327|                   0.59|               0.19|\n|set4_skewed   |           1.080|           1.125|                   0.48|               0.20|\n\n\n:::\n:::\n\n\n**Individual level: the gaps widen.** In the hierarchical setting, the model practitioners actually estimate, each respondent contributes only $T = 12$ ordinal reports and the pooled cut points no longer rescue the coarsened second stage. Across 20 paired replications, top-2-box dichotomization inflates the variance of the shared cut point by a factor of 1.09, individual-level purchase-probability prediction error by 1.19 in variance terms, and individual part-worth RMSE by 4.2%, with identical forced-choice data. Holdout hit rates are statistically indistinguishable (0.511 versus 0.510), as they should be. The first response carries the ranking information, and what dichotomization damages is precisely the demand margin the dual response exists to measure.\n\n### Specification Tests: Size and Power {#sec-sim-spectests}\n\n[Notebook 5](notebooks/05-specification-tests.qmd) turns the two behavioral claims of @sec-spectests into one-parameter extensions of the likelihood and establishes their operating characteristics over 300 (size) and 150 (power) replications per cell. Both tests hold their nominal 5% size and the estimators of $\\lambda$ and $\\delta$ are unbiased (@tbl-spec).\n\nTwo results deserve emphasis. The conditioning test rejects the DR-2Max second stage in *every* replication at both sample sizes, so the 2Max-versus-inclusive-value question does not require large data to settle. And the test is informative in both directions: when the data truly come from a DR-2Max process, $\\hat\\delta$ lands on 1 (mean 1.00) and our model is rejected with power 100%. Against slope alternatives the $\\lambda$ test has power 99% at 3,600 tasks but only 64% at 1,200, which is a design fact worth knowing before fielding a study intended to test the unit-slope claim.\n\n\n::: {#tbl-spec .cell tbl-cap='Rejection rates of nominal-5% likelihood-ratio specification tests. Under the null (top rows), the lambda and delta tests hold size while \\'delta = 1\\' shows power against DR-2Max; under the alternatives (bottom rows), the targeted test rejects while the others stay quiet. Full study in notebook 5.'}\n\n```{.r .cell-code .hidden}\nsp <- do.call(rbind, lapply(spec$cells, function(cl)\n  data.frame(cell = cl$label, n = cl$n,\n             `reject lambda=1` = round(cl$reject[1], 3),\n             `reject delta=0` = round(cl$reject[2], 3),\n             `reject delta=1 (2Max)` = round(cl$reject[3], 3),\n             check.names = FALSE)))\nknitr::kable(sp, row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|cell                 |    n| reject lambda=1| reject delta=0| reject delta=1 (2Max)|\n|:--------------------|----:|---------------:|--------------:|---------------------:|\n|size B               | 1200|           0.067|          0.050|                 1.000|\n|size B               | 3600|           0.063|          0.027|                 1.000|\n|size A               | 3600|           0.047|          0.033|                 1.000|\n|power lambda=0.7     | 3600|           0.993|          0.053|                 1.000|\n|power lambda=1.3     | 3600|           0.993|          0.060|                 1.000|\n|power lambda=0.7     | 1200|           0.640|          0.053|                 1.000|\n|power 2max (delta=1) | 3600|           0.067|          1.000|                 0.073|\n|power 2max (delta=1) | 1200|           0.060|          1.000|                 0.053|\n\n\n:::\n:::\n\n\n### Misspecification Robustness {#sec-sim-robust}\n\n[Notebook 6](notebooks/06-misspecification.qmd) breaks the model five ways, each time generating data from something the model does not describe and fitting the model anyway on hierarchical panels.\n\n- **Wrong link.** Fitting the logistic link to data from our model and vice versa moves holdout purchase-probability predictions by at most 0.025 on the probability scale, versus 0.019 under the correct link, and WAIC selects the true link in 100% of replications at this design's attractiveness spread. Link misspecification is a second-order concern for demand; it matters for extrapolation into the tails.\n- **Ignored scale-usage heterogeneity.** With respondent-specific cut points in the data-generating process (dispersion 0.35 on $c_{i1}$), the common-cut model loses almost nothing: individual part-worth RMSE 0.532 versus 0.535 for the heterogeneous-cut model, with prediction and hit-rate differences equally negligible. At commercial task counts the extension of @sec-hetcut is robustness insurance and a diagnostic, not a default, which is what the identification discussion anticipated.\n- **Non-Gumbel errors.** With variance-matched normal first-stage errors, preference recovery and demand prediction are essentially unimpaired (individual RMSE 0.514, prediction RMSE 0.110); the misspecification is absorbed almost entirely by the cut-point locations, with the top-2-box cut shifting by 0.63.\n- **Correlated alternatives.** Appendix D shows that the framework survives any GEV error structure once the inclusive value is redefined, so fitting the independent-Gumbel model to nested-logit data misspecifies exactly one thing: it uses $\\ln \\sum_j e^{V_j}$ where the truth is $\\ln G(e^{V})$. With four alternatives in two nests at dissimilarity $0.5$ (within-nest error correlation $0.75$), holdout demand prediction is unaffected (RMSE 0.110 against 0.111 under correct specification), and individual part-worth RMSE rises only to 0.553 from 0.524. The damage is again absorbed by the cut points, and in the direction theory predicts: nesting makes $G(e^{V}) < \\sum_j e^{V_j}$, so the fitted model overstates the inclusive value and the top-2-box cut compensates upward by 0.21.\n- **Task-order drift.** When the outside good drifts across the sequence (linear drift, and Hung-style probabilistic updating as in @Hung_2025_nochoice), the static model's cut points absorb the average drift while part-worths remain accurate, and a simple order diagnostic, residual exceedance regressed on task position, detects the drift reliably (mean $|t| = 5.1$ under linear drift).\n\nA pattern runs through all five: the damage lands on the cut points rather than on the preference parameters or the demand quantities built from them. The reason is structural rather than lucky. The forced choice identifies preferences and none of these misspecifications touch it, while the cut points are the model's only free location and absorb whatever the second stage cannot express. The implication cuts both ways. Demand estimates are robust; the *structural* reading of the cut points as probability thresholds, which is what gives scale labels quantitative meaning, is the fragile part.\n\n### Designing the Scale {#sec-sim-design}\n\n[Notebook 7](notebooks/07-scale-design.qmd) turns the information results of @sec-information into design guidance (@fig-infoW). With cut points at equal expected shares, a binary follow-up captures 46% of the continuous-report information limit and five points capture 78%; the increment beyond seven points is small. Cut *placement* matters as much as cut *count*: information-optimal cuts recover a further 15% over equal-share placement, and label sets that produce the skewed usage typical of fielded purchase-intent scales cost 29% relative to optimal.\n\n\n::: {#cell-fig-infoW .cell}\n\n```{.r .cell-code .hidden}\nknitr::include_graphics(file.path(\"R\", \"output\", \"figs\", \"info_by_W.png\"))\n```\n\n::: {.cell-output-display}\n![Share of the continuous-report information captured by a W-point second response (cut points at equal expected shares). The binary response is the least informative member of the family; most of the gap closes by five points. From notebook 7.](R/output/figs/info_by_W.png){#fig-infoW width=700}\n:::\n:::\n\n\n### Economic Stakes: A Pricing Counterfactual {#sec-sim-counterfactual}\n\nFinally, [notebook 8](notebooks/08-pricing-counterfactual.qmd) pushes each estimator through the decision it exists to inform. A synthetic market of five brands with a quality attribute, wide price variation, and heterogeneous preferences calibrated to own-price elasticities of about -1.9 generates $W = 5$ dual-response data ($N = 500$, $T = 12$); each estimator's demand system then sets Nash equilibrium prices by damped best responses, verified from multiple starts. Demand is defined identically for all systems as top-2-box purchase, so the well-placed binary estimator is answering exactly the right question, and posterior-predictive demand uses full parameter draws rather than posterior means, which would flatten heterogeneity.\n\n\n::: {#tbl-counterfactual .cell tbl-cap='Nash-pricing distortions by estimator: mean and max absolute equilibrium-price error versus the true equilibrium; error in the system\\'s own profit forecast at its equilibrium; and realized profit forgone relative to pricing at the true equilibrium. Full study in notebook 8.'}\n\n```{.r .cell-code .hidden}\nknitr::kable(cf$distortions, row.names = FALSE,\n             col.names = c(\"system\", \"mean |price err| %\", \"max |price err| %\",\n                           \"profit forecast err %\", \"profit forgone %\"))\n```\n\n::: {.cell-output-display}\n\n\n|system      | mean &#124;price err&#124; %| max &#124;price err&#124; %| profit forecast err %| profit forgone %|\n|:-----------|----------------------------:|---------------------------:|---------------------:|----------------:|\n|ordinal     |                         1.11|                        2.13|                 -2.98|             0.37|\n|bin_t2b     |                         1.10|                        2.38|                 -2.47|            -0.31|\n|bin_top     |                         2.57|                        5.73|                -59.29|            -0.84|\n|heur_juster |                         4.84|                        8.52|                105.82|             2.18|\n|heur_t2b    |                         4.84|                        8.52|                 52.94|             2.18|\n\n\n:::\n:::\n\n\nThree lessons (@tbl-counterfactual). First, the full ordinal model prices the market almost exactly. Second, the *well-placed* binary dual response also prices well, consistent with the efficiency analysis, but the analyst does not get to choose the placement after the fact: dichotomizing at the top box misprices by up to 5.7% and misstates its own profit forecast by 59%, because a top-box model can only answer a top-box question. Third, the constant-probability heuristic is the expensive shortcut. Its purchase incidence cannot respond to price, so it underprices systematically, its equilibrium being the inside-good-only equilibrium because the calibration constant cancels from every best response, and it overstates forecast profits by 106%. The heuristic's failure is structural, not statistical: the constant is the problem, so no choice of constant and no amount of data repairs it.\n\n\n## Empirical Application {#sec-analysis}\n\nWe illustrate the model with data from a commercial choice-based conjoint study conducted in partnership with a consumer insights consultancy, in which each choice task was followed by an ordinal purchase-likelihood question.\n\n<!-- TODO [DATA — Dan to locate]: this section is fully structured but awaits the GBK study data. Fill in: product category, sample size and recruitment/screening, number of tasks and alternatives per task, attribute list and levels, the exact wording and number of points (W) of the purchase-likelihood question, and fielding dates. -->\n\n### Data {#sec-data}\n\n<!-- TODO: describe the study. Include (1) a table of attributes and levels; (2) descriptive statistics: distribution of the ordinal responses overall and by task order (any drift across tasks connects to @Hung_2025_nochoice); (3) model-free evidence that the ordinal response co-moves with task attractiveness — e.g., mean response plotted against the estimated inclusive value or against simple proxies like number of low-priced options — which is the reduced-form signature of @eq-cumlink and motivates the structural model. -->\n\n### Model Specifications and Estimation {#sec-empirical-spec}\n\nWe estimate four specifications on the same data: our model (@sec-model) in aggregate and hierarchical form; the binary dual-response benchmark applied to the dichotomized scale (top-two-box); and the constant-probability heuristic. Hierarchical specifications use the sampler of @sec-estimation.\n\n**Pre-specified test battery.** Before any model comparison, we commit to the three specification tests of @sec-spectests on the aggregate fit: the unit-slope test ($\\lambda = 1$), the conditioning test ($\\delta = 0$), and the DR-2Max test ($\\delta = 1$) — whose operating characteristics are established in @sec-sim-spectests — together with the A-versus-B link comparison by holdout likelihood and WAIC. We also pre-commit to re-running the pricing counterfactual of @sec-sim-counterfactual on the empirical posteriors, replacing the synthetic market with the study's own category structure.\n\n<!-- TODO: report MCMC settings (iterations, burn-in, thinning), convergence diagnostics (appendix), and holdout design (withheld tasks per respondent). -->\n\n### Results {#sec-empirical-results}\n\n<!-- TODO: results, mirroring the simulation-study structure so the reader can map findings across sections:\n(1) Model comparison: LMD for all specifications — headline question: which link (A vs. B) fits real respondents better, and how much does the ordinal model improve on the dichotomized binary model?\n(2) Parameter estimates: part-worths across specifications (expect: attribute part-worths broadly stable, in line with Brazell_2006 and Hung_2025_dual; differences concentrated in the outside-good/cut-point structure); estimated cut points with interpretation — what purchase probability does each scale label correspond to (our model's alphas are directly interpretable here and are a selling point of the framework).\n(3) Predictive validity: holdout hit rates and predicted vs. actual ordinal response distributions.\n(4) Managerial quantities: purchase-incidence/share predictions across methods — show how much the dichotomization choice (top-box vs. top-two-box) moves the answer vs. the model-based estimate.\n(5) If task-order drift appears in the descriptives, a robustness fit with task-number effects, connecting to Hung_2025_nochoice. -->\n\n### Scale-Usage Heterogeneity {#sec-empirical-hetcut}\n\n<!-- TODO: estimate the heterogeneous-cut-point extension (@sec-hetcut) on the empirical data; report the estimated dispersion of theta_i (how differently do real respondents use the scale?), the correlation between scale usage and preferences, and the effect on managerial quantities of accounting for it. -->\n\n\n## Discussion {#sec-discussion}\n\n### What the Behavioral Model Changes\n\nThe premise that the consumer observes everything about the inside goods but not the outside-good shock does more than motivate a likelihood; it reorganizes how the dual-response literature's models relate to one another. In the binary literature, the choice between DR-2Max and DR-AnyMax was framed as a question about the second question's wording — whether the respondent evaluates her selected option or the whole set [@Diener_2006] — and the shared-error Unified Model of @Hung_2025_dual was motivated by the internal consistency of a single utility draw. Our framework arrives at the inclusive-value form from the primitive assumption about information: because the maximum of Gumbel utilities is independent of which good attains it, *any* coherent report about the best option's standing against the outside good must depend on the task only through its inclusive value. The empirical success of the AnyMax/Unified form over DR-2Max, documented in both @Diener_2006 and @Hung_2025_dual, is what this framework predicts. Where our account differs from @Brazell_2006 is in what the second response *is*: not a second choice from an augmented set, but a report about an unresolved comparison — which is what licenses asking for it on an ordinal scale in the first place.\n\nThe choice of link is, likewise, a substantive behavioral question dressed as a specification detail. It is also a question with a definite scope. For a binary follow-up both accounts are coherent and they disagree: resolving the outside-good draw first recovers the standard logit second stage, while our model implies a complementary log-log one even for yes/no data. Because the two diverge mainly in the tails, telling them apart requires either large samples or designs with wide variation in task attractiveness; @sec-analysis provides evidence from one commercial dataset, and we regard the question as open and worth testing on the many existing binary dual-response datasets, where our model's binary case can be estimated with a one-line change to current code. For an ordinal follow-up the question does not arise in the same form, since a respondent who has resolved the outside good holds no graded likelihood to report.\n\n### Implications for Practice\n\nFour points bear directly on applied work. First, if an ordinal dual response has been fielded, dichotomizing it is costly and arbitrary: the analyst's choice of cut is made before seeing the data, the penalty ranges from a few percent of sample at a lucky cut to a third of it at an unlucky one (@sec-sim-benchmarks), the damage concentrates at the individual level where hierarchical estimation lives, and a dichotomized model can answer questions only at its own threshold — the pricing counterfactual's top-box analyst misstates the profit forecast by more than half for exactly that reason. Second, constant-probability weighting has a *structural* flaw, not a statistical one: beyond the set-dependence of scale-point meaning (@eq-condexp and @tbl-toy), a fixed purchase incidence cancels out of every pricing first-order condition, so the heuristic's price recommendations ignore the no-buy margin entirely — no amount of data fixes this. Third, the information results in @sec-information and @sec-sim-design give concrete design guidance: five scale points capture most of the binary-to-continuous information gap (about 78%, versus 46% for binary), gains beyond seven points are small, and *where* the labels place the cut points matters as much as how many there are. Fourth, studies that intend to test the behavioral model (the link, the unit slope) should engineer variation in task attractiveness; designs without it cannot discriminate the links even in principle (@sec-identification), a fact our squashed-design experiment confirms empirically.\n\n### Relation to the Outside-Good Literature\n\nOur model holds the outside good's *mean* utility fixed at zero and locates all action in the consumer's uncertainty about its realization. Two adjacent strands suggest natural extensions. @Hung_2025_dual show that a budget constraint applied to the second response — but not the forced choice — improves fit and materially changes equilibrium price predictions; the same asymmetric treatment is available here, censoring the ordinal report for options priced above a respondent-level budget, and the ordinal response should sharpen the identification of that budget since near-threshold options will earn lukewarm rather than merely negative reports. @Hung_2025_nochoice document that the no-choice option's utility can drift over the course of a survey as respondents learn about the category; in our notation this is drift in the cut points (or in the outside-good location), and the task-order diagnostics of @sec-data carry over directly. More broadly, the opt-out literature's warning that a single constant rarely captures heterogeneous non-purchase behavior [@Campbell_2019; @Haaijer_2001] applies to the dual response as well; the heterogeneous-cut-point extension of @sec-hetcut is one response, and richer structures (e.g., serial non-purchasers as a latent class) are compatible with the framework.\n\n### Limitations\n\nFive limitations qualify the results. First, the Gumbel error assumption is load-bearing: the factorization of the joint likelihood and the inclusive-value form of the second response both rest on max-stability. Appendix D shows how far this can be pushed. Any generalized extreme value structure, nested logit included, preserves both properties once the inclusive value is redefined as the GEV generator, so correlation among the displayed alternatives costs the framework nothing. Error families outside that class do break the closed form: under a probit or a mixed logit with a correlated kernel the max utility has no closed-form distribution, and the second response would require simulation over it. Our robustness experiments soften the concern in one direction: with variance-matched normal errors, preference and demand estimates are essentially unimpaired, the misspecification being absorbed by the cut-point locations — so structural interpretation of the cut points deserves more caution than the demand quantities built from them. Second, we treat tasks as independent draws, abstracting from learning, fatigue, and reference formation across the sequence [@Hung_2025_nochoice]; the task-order diagnostic of @sec-sim-robust detects such drift reliably when present. Third, the common-cut-point model assumes a shared reading of the scale labels; the extension of @sec-hetcut relaxes this, but individual-level identification is thin at commercial task counts, and our simulations find that ignoring moderate scale-usage heterogeneity costs little — the extension earns its keep as insurance and as a diagnostic, not as a default. Fourth, like all stated-preference methods, the model calibrates stated rather than revealed purchase behavior; the ordinal report inherits whatever hypothetical bias attends purchase-intent questions generally [@Morrison_1979], and linking the estimated cut points to realized purchase rates — the ordinal analogue of the calibration literature on binary intentions — is a natural next step. Fifth, the likelihood presumes the two questions are asked together, as in the standard dual-response task. Designs that separate them, such as the separated dual response of @Schlereth_2017, break the coupling between the two responses and would require the stages to be modeled as separate draws. A separate methodological caution, documented in Appendix C, is that harmonic-mean marginal-likelihood estimates are optimistic; we therefore anchor model comparisons in holdout likelihood and WAIC alongside the conventional estimator.\n\n\n## Conclusion {#sec-conclusion}\n\nDual-response conjoint separates a question consumers answer readily, which of these do you like best, from one they cannot answer with certainty, would you actually buy it. This paper takes that uncertainty as the modeling primitive. A consumer who observes everything about the displayed alternatives but not her valuation of the outside good holds a purchase probability rather than a decision, so the natural follow-up question is ordinal and the natural model joins a multinomial logit for the forced choice to a cumulative-link ordinal model on the task's inclusive value. The link function is not a modeling choice. It follows from whether the respondent reports the probability she still holds, as our model has her do, or resolves her uncertainty and grades the comparison that results, and the two are distinguishable on data that vary the attractiveness of the displayed alternatives.\n\nThree results follow. At two scale points the logistic link is the incumbent binary dual-response model, so the ordinal form is an extension of that literature rather than a departure from it, while our model's binary case is a complementary log-log response, which implies that the familiar yes/no follow-up is mildly misspecified and can be checked on data already collected. A finer scale never subtracts information, and five points capture most of the gap between a binary answer and a continuous one. The two ways an ordinal report is otherwise reduced to something the binary model accepts, collapsing the scale at an arbitrary point and assigning each point a fixed purchase probability, are respectively wasteful and internally inconsistent, the second because the meaning of a scale label depends on what was on the screen. Simulation evidence confirms that the aggregate and hierarchical Bayesian estimators recover the model's parameters, including the cut points that give the scale labels quantitative meaning, and that the conclusions survive correlated alternatives, non-Gumbel errors, and drift in the outside good across a respondent's task sequence.\n\n<!-- TODO: add one sentence on what the empirical application shows, once the GBK data are in hand (@sec-analysis is structured but not yet estimated). -->\n\nThe broader point is that a response format and the model that reads it belong together. A finer scale is worth fielding only if something can use the extra categories, and a model is worth deriving only if the question it reads is one respondents can answer. Supplying the likelihood makes the ordinal follow-up a measurement instrument rather than a longer question, and it opens work on calibrating estimated cut points against realized purchase behavior, on using the ordinal response to identify budget constraints, and on the design of the scale itself.\n\n\n## Appendix A: Proofs {#sec-appendix-proofs .unnumbered}\n\n### A.1 Proof of @lem-gumbel {.unnumbered}\n\nThe result is classical [@Mcfadden_1981]. We give the derivation because part (ii) carries @eq-joint, and because Appendix D generalizes precisely this calculation to generalized extreme value errors.\n\nLet $u_j = V_j + \\eta_j$ with $\\eta_j \\iid \\text{Gumbel}(0,1)$ for $j \\in \\mathcal{J}^+$, so $u_j$ has CDF $F_j(t) = \\exp\\left( -e^{-(t - V_j)} \\right)$ and density $f_j(t) = e^{-(t-V_j)} \\exp\\left( -e^{-(t-V_j)} \\right)$. For any $j$ and any $u$,\n$$\n\\Pr \\left( j^* = j, \\; u^* \\le u \\right)\n= \\int_{-\\infty}^{u} f_j(t) \\prod_{k \\ne j} F_k(t) \\, dt\n= \\int_{-\\infty}^{u} e^{V_j} e^{-t} \\exp \\left( -e^{-t} S \\right) dt,\n$$\nusing $\\prod_{k \\ne j} F_k(t) = \\exp\\left( -e^{-t} \\left( S - e^{V_j} \\right) \\right)$ with $S = \\sum_{k} e^{V_k}$, and collecting terms. Substituting $s = e^{-t} S$ (so $ds = -e^{-t} S \\, dt$) gives\n$$\n\\Pr \\left( j^* = j, \\; u^* \\le u \\right)\n= \\frac{e^{V_j}}{S} \\int_{e^{-u} S}^{\\infty} e^{-s} \\, ds\n= \\underbrace{\\frac{e^{V_j}}{S}}_{\\Pr\\left(j^*=j\\right)} \\; \\times \\; \\underbrace{\\exp \\left( -S e^{-u} \\right)}_{F_{\\text{Gumbel}\\left(\\overline{\\mu},1\\right)}(u)}.\n$$\nLetting $u \\to \\infty$ delivers the MNL choice probability; summing over $j$ delivers $u^* \\sim \\text{Gumbel}(\\overline{\\mu}, 1)$ with $\\overline{\\mu} = \\ln S$; and the factorization of the joint law for every $(j, u)$ is precisely the independence of $j^*$ and $u^*$. $\\square$\n\nThe calculation above is short but gives little sense of why the two quantities separate. The following change of variable makes it transparent, and it is the same argument that generalizes to correlated alternatives in Appendix D.\n\nWrite $y_j = e^{V_j}$ and set $T_j = e^{-u_j}$. The map is decreasing, so it exchanges maxima for minima: the best good is the one with the smallest $T_j$, and $u^* = -\\ln \\min_j T_j$. Under the Gumbel assumption,\n$$\n\\Pr \\left( T_j > t \\right) = \\Pr \\left( u_j < -\\ln t \\right) = e^{-y_j t},\n$$\nso each good becomes an independent waiting time that arrives at the constant rate $y_j$, and the consumer's chosen good is whichever arrives first.\n\nFor independent waiting times of this kind, the identity of the first arrival and the time of that arrival are independent, and the reason is that the rates do not change as time passes. At any instant, given that nothing has yet arrived, the chance that the next arrival is good $j$ is $y_j / S$, the same at the start as at any later point. Which good arrives first is therefore settled entirely by the rates relative to one another, while how long the wait lasts is settled entirely by their sum $S$. Waiting longer says nothing about who will win. Transforming back, the shares $y_j / S$ are the multinomial logit probabilities and the total $S$ fixes the location of $u^*$, which is the content of @lem-gumbel. This is the division of labor between the two responses. The rates relative to one another are the utility differences that the forced choice reveals, and their sum is the inclusive value that the ordinal report reads, so the two responses read separate features of the same draw.\n\nThe same statement in utility terms is that the relative odds of being the maximizer are the same at every level of the maximum, because Gumbel upper tails decay exponentially and are therefore shift-invariant: $\\Pr(u_1 > m) / \\Pr(u_2 > m) = e^{V_1 - V_2}$ for every $m$.\n\nThis is a property of the extreme-value family and not of random utility models in general. Under normal errors with $V_1 > V_2$, the ratio of upper tails diverges as $m$ grows, so a high realized maximum is disproportionately likely to have come from the better alternative. The level of the maximum then carries information about which alternative attained it, the joint law of $\\left( j^*, u^* \\right)$ does not factor, and the counterpart of @eq-joint is unavailable. What Appendix D shows is that the factorization survives correlation among the inside goods, because the waiting times may be dependent and still arrive at rates whose ratios are constant over time; what fails outside the extreme-value family is the constancy of those ratios.\n\n### A.2 Derivation of the information increment (@eq-fisher) {.unnumbered}\n\nThe second response contributes the multinomial log-likelihood $\\ell = \\sum_w \\mathbb{1}\\lbrace y = w \\rbrace \\ln \\pi_w$ with $\\pi_w = F(c_w - \\overline{\\mu}) - F(c_{w-1} - \\overline{\\mu})$. Since $\\partial \\overline{\\mu} / \\partial \\bfbeta = \\sum_j \\Pr(j^* = j) \\, \\x_j = \\overline{\\x}$, the score with respect to $\\bfbeta$ in category $w$ is $- \\left[ f_w - f_{w-1} \\right] / \\pi_w \\cdot \\overline{\\x}$, writing $f_w = f \\left( c_w - \\overline{\\mu} \\right)$ and $f = F'$ (with $f_0 = f_W = 0$). The information is the expected outer product of the score:\n$$\n\\mathcal{I}^{(2)} = \\sum_{w=1}^{W} \\pi_w \\left( \\frac{f_w - f_{w-1}}{\\pi_w} \\right)^2 \\overline{\\x} \\, \\overline{\\x}'\n= \\left[ \\sum_{w=1}^{W} \\frac{ \\left( f_w - f_{w-1} \\right)^2 }{ \\pi_w } \\right] \\overline{\\x} \\, \\overline{\\x}'\n= \\omega \\left( \\overline{\\mu}; \\mathbf{c} \\right) \\overline{\\x} \\, \\overline{\\x}'. \\qquad \\square\n$$\nThe joint information over $\\left( \\bfbeta, \\mathbf{c} \\right)$, including the cut-point blocks used by the estimation code, follows from the same score with $\\partial \\pi_w / \\partial c_m = f_w \\mathbb{1}\\lbrace m = w \\rbrace - f_{w-1} \\mathbb{1}\\lbrace m = w-1 \\rbrace$.\n\n### A.3 Monotonicity of $\\omega$ under refinement {.unnumbered}\n\nLet $\\mathcal{C}'$ be a coarsening of the partition $\\mathcal{C}$ obtained by merging adjacent categories $w$ and $w+1$. The merged cell contributes $\\left( f_{w+1} - f_{w-1} \\right)^2 / \\left( \\pi_w + \\pi_{w+1} \\right)$ to $\\omega'$, while the two original cells contribute $\\left( f_w - f_{w-1} \\right)^2 / \\pi_w + \\left( f_{w+1} - f_w \\right)^2 / \\pi_{w+1}$ to $\\omega$. Writing $a = f_w - f_{w-1}$, $b = f_{w+1} - f_w$, $u = \\pi_w$, $v = \\pi_{w+1}$, the Cauchy–Schwarz inequality in Engel form gives\n$$\n\\frac{(a + b)^2}{u + v} \\;\\le\\; \\frac{a^2}{u} + \\frac{b^2}{v},\n$$\nso each merge weakly decreases $\\omega$, and any coarsening — being a finite sequence of adjacent merges — does the same. The binary response is the coarsest member of the family and hence the least informative; conversely, as the mesh of the partition goes to zero the interval score converges to the exact-observation score and $\\omega \\to \\int \\left( g' \\right)^2 / g \\, dz$, the Fisher information of the latent's location (equal to $1$ for the standard Gumbel and $1/3$ for the standard logistic). $\\square$\n\n## Appendix B: Estimation Details {#sec-appendix-estimation .unnumbered}\n\n**Aggregate model.** The likelihood is maximized over the working parameters $\\left( \\bfbeta, c_1, \\ln(c_2 - c_1), \\ldots, \\ln(c_{W-1} - c_{W-2}) \\right)$, which enforce cut-point monotonicity without constraints; standard errors for the cut points follow by the delta method. Interval probabilities are computed with tail-stable expressions ($\\Lambda(h)\\Lambda(-l)(1 - e^{l-h})$ for the logistic link and $e^{-e^{-h}}\\left(1 - e^{-(e^{-l} - e^{-h})}\\right)$ for the Gumbel link) so that extreme cut points do not lose precision to cancellation.\n\n**Hierarchical model.** The sampler is a random-walk Metropolis-within-Gibbs in the style of @Rossi_2005 with three blocks per iteration: (1) all respondents' $\\bfbeta_i$ (and, in the heterogeneous-cut-point extension, $\\bftheta_i$) are updated simultaneously by independent normal random-walk proposals with covariance $s_i^2 \\Sigma$; (2) the common cut-point block is updated by a random-walk proposal on the unconstrained scale; (3) the population moments $\\left( \\betabar, \\Sigma \\right)$ are drawn from their conjugate normal and inverse-Wishart conditionals. Priors: $\\betabar \\sim \\mathcal{N}\\left( \\mathbf{0}, 100 I \\right)$, $\\Sigma \\sim \\text{IW}\\left( \\dim + 3, (\\dim + 3) I \\right)$, and $\\mathcal{N}(0, 100 I)$ on the transformed cut points. Step sizes are initialized at $2.93/\\sqrt{\\dim}$ and adapted only during burn-in toward acceptance rates of $0.23$ (individual blocks) and $0.30$ (cut-point block). Unless noted, we run 30,000 iterations, discard 10,000, and keep every 10th draw.\n\nThe sampler was validated four ways (replication code accompanies the paper): parameter recovery on synthetic panels for both links; repeated-sampling coverage of 50% and 90% posterior intervals at nominal rates; agreement of the forced-choice-only special case with an independent hierarchical-MNL implementation (posterior means matching to less than 0.01 on all hyperparameters on common data); and convergence of the posterior toward the aggregate MLE when the data are generated without heterogeneity.\n\n## Appendix C: Marginal-Likelihood Estimation {#sec-appendix-lmd .unnumbered}\n\nModel comparisons in the paper report the log marginal density (LMD). For hierarchical models we follow the standard practice in this literature [@Hung_2025_dual] and use the harmonic-mean estimator of @Newton_1994, complemented by two quantities that do not rely on it: the WAIC computed from pointwise per-respondent likelihoods [@Watanabe_2010; @Vehtari_2017] and the log posterior-predictive density of held-out tasks. The reason for the complements is that the harmonic-mean estimator is optimistic. In the aggregate model — where the parameter space is small enough for exact methods — we can quantify this directly: bridge sampling [@Meng_1996; @Gronau_2020] and a Laplace approximation agree with each other to well under one log point, while the Newton–Raftery estimate exceeds them by dozens of log points, and trimming the smallest-likelihood draws widens rather than closes the gap:\n\n\n::: {#tbl-lmd-check .cell tbl-cap='Aggregate-model log marginal density by estimator (simulated data, n = 3,600 tasks; from notebook 03).'}\n\n```{.r .cell-code .hidden}\nhv <- readRDS(file.path(\"R\", \"output\", \"hb_validation.rds\"))\nknitr::kable(transform(hv$lmd_check, lmd = round(lmd, 2)), row.names = FALSE,\n             col.names = c(\"estimator\", \"log marginal density\", \"vs. bridge\"))\n```\n\n::: {.cell-output-display}\n\n\n|estimator   | log marginal density| vs. bridge|\n|:-----------|--------------------:|----------:|\n|bridge      |             -9844.14|       0.00|\n|laplace     |             -9844.15|      -0.01|\n|NR          |             -9801.78|      42.36|\n|NR trim 5%  |             -9799.63|      44.51|\n|NR trim 20% |             -9798.42|      45.73|\n\n\n:::\n:::\n\n\nBecause the bias is similar for models of similar dimension, Newton–Raftery *rankings* between the ordinal and binary dual-response models are typically preserved — but we treat the WAIC and holdout comparisons as primary whenever the two disagree.\n\n## Appendix D: Correlated Alternatives {#sec-appendix-gev .unnumbered}\n\n@lem-gumbel is stated for independent Gumbel errors, and the whole of @sec-model rests on it. This appendix shows that both of its properties hold for the entire generalized extreme value (GEV) family of @Mcfadden_1981, so that correlation among the inside goods costs the framework nothing beyond a redefinition of the inclusive value.\n\nLet the inside-good components have the GEV joint distribution\n$$\n\\Pr \\left( \\eta_1 \\le e_1, \\ldots, \\eta_J \\le e_J \\right)\n= \\exp \\left( - G \\left( e^{-e_1}, \\ldots, e^{-e_J} \\right) \\right),\n$$ {#eq-gevcdf}\nwhere the generator $G : \\mathbb{R}^J_{+} \\to \\mathbb{R}_{+}$ is homogeneous of degree one, tends to infinity in each argument, and has mixed partial derivatives that alternate in sign. Independent Gumbel errors are the special case $G(y) = \\sum_j y_j$. Write $y_j = \\exp(V_j)$, $G_j = \\partial G / \\partial y_j$, and\n$$\nS^{G} \\coloneqq G \\left( y_1, \\ldots, y_J \\right),\n\\qquad\n\\overline{\\mu} \\coloneqq \\ln S^{G}.\n$$ {#eq-gevmu}\n\n::: {#lem-gev}\nUnder @eq-gevcdf, with $u_j = V_j + \\eta_j$ and $u^* = \\max_{j} u_j$:\n\n(i) $u^* \\sim \\text{Gumbel} \\left( \\overline{\\mu}, 1 \\right)$ with $\\overline{\\mu} = \\ln S^{G}$;\n\n(ii) $j^*$ and $u^*$ are statistically independent, with $\\Pr(j^* = j) = y_j G_j(y) / S^{G}$.\n:::\n\n::: {.proof}\nThe joint CDF of the utilities is\n$$\nH \\left( m_1, \\ldots, m_J \\right)\n= \\exp \\left( - G \\left( y_1 e^{-m_1}, \\ldots, y_J e^{-m_J} \\right) \\right).\n$$\nFor (i), set every $m_j = m$ and use homogeneity of degree one: $G(y e^{-m}) = e^{-m} G(y)$, so $H(m, \\ldots, m) = \\exp \\left( - e^{-m} S^{G} \\right)$, which is the $\\text{Gumbel}\\left(\\ln S^{G}, 1\\right)$ CDF.\n\nFor (ii), write $t_k = y_k e^{-m_k}$ and differentiate:\n$$\n\\frac{\\partial H}{\\partial m_j}\n= \\exp \\left( -G(t) \\right) \\, G_j(t) \\, y_j e^{-m_j}.\n$$\nBecause $G$ is homogeneous of degree one, $G_j$ is homogeneous of degree zero, so evaluating at $m_k = s$ for every $k$ gives $G_j(t) = G_j(y)$ and $G(t) = e^{-s} S^{G}$. Hence\n$$\n\\left. \\frac{\\partial H}{\\partial m_j} \\right|_{m_k = s \\ \\forall k}\n= \\exp \\left( - e^{-s} S^{G} \\right) G_j(y) \\, y_j e^{-s}\n= \\frac{y_j G_j(y)}{S^{G}} \\cdot \\frac{d}{ds} \\exp \\left( - e^{-s} S^{G} \\right),\n$$\nand integrating from $-\\infty$ to $u$,\n$$\n\\Pr \\left( j^* = j, \\ u^* \\le u \\right)\n= \\underbrace{\\frac{y_j G_j(y)}{S^{G}}}_{\\Pr \\left( j^* = j \\right)}\n\\; \\times \\;\n\\underbrace{\\exp \\left( - e^{-u} S^{G} \\right)}_{\\Pr \\left( u^* \\le u \\right)}\n$$\nfor every $j$ and every $u$, which is the claimed independence. Letting $u \\to \\infty$ recovers the GEV choice probability. $\\square$\n:::\n\nEverything in @sec-model follows with $S_{it}$ replaced by $S^{G}_{it}$. The first response becomes the GEV choice probability rather than the multinomial logit; the second response is unchanged in form, since @eq-modelA, @eq-modelB, and the cumulative-link representation @eq-cumlink depend on the choice set only through $\\overline{\\mu}_{it}$; and the factorization @eq-joint holds for the same reason as before. The location invariance behind @prp-ident also survives: shifting every $V_{itj}$ by $\\delta$ multiplies $S^{G}_{it}$ by $e^{\\delta}$ and so shifts $\\overline{\\mu}_{it}$ by exactly $\\delta$, which the cut points absorb. The rank condition must then be read against the design as it enters $G$ rather than a simple sum, and the nesting result of @sec-nesting becomes $\\Pr(\\text{buy}) = S^{G}_{it} / \\left( e^{\\gamma} + S^{G}_{it} \\right)$.\n\nThe leading application is nested logit, $G(y) = \\sum_{n} \\left( \\sum_{j \\in n} y_j^{1/\\lambda_n} \\right)^{\\lambda_n}$, in which alternatives within a nest are correlated whenever $\\lambda_n < 1$. We confirm @lem-gev numerically for a five-alternative, two-nest design with $\\lambda = (0.5, 0.8)$ using the positive-stable mixture representation of the nested logit (`R/homogeneous/gev_check.R`). Across two million draws the simulated distribution of $u^*$ matches $\\text{Gumbel}(\\ln S^{G}, 1)$ (location $1.845$ against $1.846$ analytically; Kolmogorov-Smirnov $p = 0.17$), the simulated choice shares match $y_j G_j / S^{G}$ to four decimal places, and the conditional distribution of $u^*$ given $j^*$ is indistinguishable from its unconditional counterpart at every quartile (chi-square test of independence, $p = 0.70$).\n\nTwo limits of the result are worth stating. It covers correlation among the *inside* goods only: the outside-good shock $\\eta_{it0}$ is assumed independent of them throughout, and The logistic link uses that independence to obtain $d_{it} \\sim \\text{Logistic}(\\overline{\\mu}_{it}, 1)$. And it does not extend to error structures outside the GEV class, such as multinomial probit or a mixed logit with correlated kernel errors, for which $u^*$ has no closed-form distribution and the factorization that makes @eq-joint tractable is unavailable.\n\n## Appendix E: Implementation in Apollo {#sec-appendix-apollo .unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nap <- readRDS(file.path(\"R\", \"output\", \"apollo_compare.rds\"))\n```\n:::\n\n\nThe replication archive implements the model twice: once directly, in the routines described in Appendix B, and once in Apollo [@Hess_2019], the freeware choice-modelling package for R. The second implementation serves two purposes. It cross-validates our code against an independently developed and widely used toolkit, and it shows how the model fits into an estimation framework readers are likely to already have installed.\n\n**The model as a two-component structure.** Apollo builds a likelihood by multiplying components. Our joint likelihood @eq-joint is exactly of that form, so the forced choice is an `apollo_mnl` component and the ordinal follow-up is a second component over the same tasks. This is the architecture of the hybrid choice models for which the package is often used, in which a multinomial logit for the choice is combined with ordered-response components for attitudinal indicators [@Daly_2012]. The resemblance is worth being precise about, because the difference is the content of @sec-model. In a hybrid choice model the ordinal component is driven by a latent attitude that is exogenous to the choice, and it is connected to the choice utilities through freely estimated loading parameters. Here the ordinal component is driven by the inclusive value of the same choice set, and its loading is fixed at one rather than estimated. Our model is the restricted case, and @lem-gumbel is what licenses the restriction.\n\n**The logistic specification is native; ours is not.** With the second stage a cumulative logit in $\\overline{\\mu}_{it}$, The logistic specification is assembled from stock parts: `apollo_mnl` for the choice, `apollo_ol` for the follow-up with the task's inclusive value passed as its single explanatory variable and the cut points as its thresholds, and `apollo_combineModels` to join them. Our model has no stock part. Apollo supplies ordered components for the logistic and normal links and no others, so the complementary-log-log form @eq-modelA must be written out and passed through `apollo_ownModel`, the hook for user-defined likelihoods. This is a small piece of code, and once supplied it inherits the rest of the package. The asymmetry is worth noting for its own sake: the standard toolkit anticipates the behavior in which the respondent resolves her uncertainty before answering, and not the behavior in which she reports the probability she still holds.\n\n**Agreement.** @tbl-apollo reports the largest discrepancy between the two implementations over 5 independent datasets of 2,000 tasks in each of two configurations, with both implementations started from the same values.\n\n\n::: {#tbl-apollo .cell tbl-cap='Largest absolute discrepancy between our maximum-likelihood routine and the same model estimated in Apollo, over five independent datasets per configuration (from R/apollo/compare_apollo.R).'}\n\n```{.r .cell-code .hidden}\ntb <- ap$res[c(2, 3), ]\ntb$configuration <- c(\"Our model, W = 5\", \"Logistic, W = 2 (binary)\")\nsci <- function(x) sprintf(\"%.0e\", x)\nknitr::kable(\n  data.frame(\n    configuration = tb$configuration,\n    `ordinal component` = tb$component,\n    `beta` = sci(tb$max_d_beta),\n    `cut points` = sci(tb$max_d_cut),\n    `standard errors` = sci(pmax(tb$max_d_se_beta, tb$max_d_se_cut)),\n    `log-likelihood` = sci(tb$max_d_ll),\n    check.names = FALSE),\n  row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|configuration            |ordinal component |beta  |cut points |standard errors |log-likelihood |\n|:------------------------|:-----------------|:-----|:----------|:---------------|:--------------|\n|Our model, W = 5         |apollo_ownModel   |1e-06 |2e-06      |1e-07           |9e-10          |\n|Logistic, W = 2 (binary) |apollo_ol         |5e-07 |5e-07      |5e-09           |6e-11          |\n\n\n:::\n:::\n\n\nPoint estimates agree to 2e-06 or better, standard errors to 1e-06, and the maximized log-likelihood to 9e-10, which is convergence tolerance rather than disagreement. The two implementations share no code: Apollo computes the ordinal probabilities for our model from the direct expression $e^{-e^{-(c_w - \\overline{\\mu})}} - e^{-e^{-(c_{w-1} - \\overline{\\mu})}}$, while ours uses the tail-stable rearrangement of Appendix B, and the cut points enter Apollo's likelihood as free parameters rather than through the monotone increment parameterization. The binary row is the incumbent dual-response model of @Diener_2006 and @Hung_2025_dual, recovered as the two-point special case of @sec-nesting.\n\n**Why the hierarchical model is not estimated in Apollo.** Apollo reaches Bayesian estimation by wrapping `RSGHB`, which requires each random parameter to be assigned one of a fixed menu of marginal distributions: normal, log-normal, censored normal, or Johnson SB. None of them can express an ordered vector. The heterogeneous-cut-point extension of @sec-hetcut gives each respondent her own thresholds $\\bftheta_i$, which must stay ordered for the likelihood to be defined, and we impose that through a transformation to an unconstrained scale inside a random-walk block. That is expressible in a purpose-written sampler and not in the `RSGHB` menu. The restriction is specific to the Bayesian path: `apollo_ol` accepts thresholds that vary across observations, so classical mixed-threshold specifications are available. This is the reason the hierarchical results in @sec-simstudy come from the sampler of Appendix B rather than from Apollo.\n\n\n## Declaration of generative AI and AI-assisted technologies in the manuscript preparation process {.unnumbered}\n\nDuring the preparation of this work the authors used Claude (Anthropic), accessed through Claude Code, iteratively in the drafting and editing of manuscript text and select coding tasks. After using this tool, the authors reviewed and edited the content as needed and take full responsibility for the content of the published article.\n\n\n\n\n\n## References {.unnumbered}\n\n::: {#refs}\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}