{
  "hash": "3810dc92e60ec451905dafed2fe2b9d4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Persistent Outside Option\"\nsubtitle: \"When the outside-good shock is drawn once per respondent instead of once per task\"\nauthor:\n  - name: Dan Yavorsky\n  - name: Geoffery Zheng\ndate: last-modified\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.content-hidden unless-format=\"html\"}\n$$\n  \\newcommand{\\x}{\\mathbf{x}}\n  \\newcommand{\\bfbeta}{\\boldsymbol{\\beta}}\n  \\newcommand{\\betabar}{\\bar{\\bfbeta}}\n  \\newcommand{\\bftheta}{\\boldsymbol{\\theta}}\n  \\newcommand{\\iid}{\\stackrel{iid}{\\sim}}\n  \\newcommand{\\coloneqq}{\\mathrel{:=}}\n$$\n:::\n\n::: {.content-hidden unless-format=\"pdf\"}\n```{=latex}\n  \\newcommand{\\x}{\\mathbf{x}}\n  \\newcommand{\\bfbeta}{\\boldsymbol{\\beta}}\n  \\newcommand{\\betabar}{\\bar{\\bfbeta}}\n  \\newcommand{\\bftheta}{\\boldsymbol{\\theta}}\n  \\newcommand{\\iid}{\\stackrel{iid}{\\sim}}\n```\n:::\n\n\n## What this notebook does\n\nModel B says the consumer resolves her outside-good shock and grades the\nrealized comparison $d_{it} = u^*_{it} - \\eta_{it0}$. Written that way, the\nshock carries a task subscript: she gets a fresh draw on every screen.\n\nThat is a strong assumption, and an easy one to miss. The inside goods\nlegitimately get new shocks each task, because each task shows new goods. But\nthe outside option is *the same object* on all of a respondent's screens. It is\nher current product, her budget this month, her situation. Re-randomizing it\nbetween screens four and five is hard to defend once stated out loud.\n\nSo consider the alternative: one outside-good shock per respondent,\n\n$$\nd_{it} = u^*_{it} - \\eta_{i0}, \\qquad \\eta_{i0} \\sim \\text{Gumbel}(0,1),\n$$\n\ndrawn once and held across her tasks. Call this the **persistent** outside\noption, against Model B's **transient** one.\n\nThe two are harder to tell apart than they look, and that is the point of this\nnotebook:\n\n1. **They are marginally identical.** Task by task, both give the logistic\n   link. A cross-section cannot distinguish them at all.\n2. **They differ in the panel.** The persistent version induces correlation\n   across a respondent's ordinal answers that the transient version does not.\n3. **The theory pins a number.** A persistent Gumbel shock implies a\n   respondent-level variance of exactly $\\pi^2/6 \\approx 1.645$ — no free\n   parameter. We estimate that variance freely and ask whether the data agree.\n4. **Ignoring it has a cost**, and we measure it.\n\nThis notebook is the source of `persistent_outside.rds`. It backs the\npersistent-outside-option paragraph in the model section.\n\n::: {.callout-note}\n## Why this is the heterogeneous-cut-point model in disguise\n\nConditional on $\\eta_{i0}$, the second-response probability is\n\n$$\n\\Pr(y_{it} \\le w \\mid \\eta_{i0}) = F\\big(c_w + \\eta_{i0} - \\overline\\mu_{it}\\big),\n$$\n\nModel A's link with every cut point shifted by the same amount. So the\npersistent outside option is exactly **location-only cut-point heterogeneity**:\nthe spacings between a respondent's thresholds are common, only the level\nmoves, and the theory fixes the level's distribution rather than estimating it.\n\nTwo consequences we lean on below. The estimator is the heterogeneous-cut\nsampler restricted to a common shift, so no new machinery is required. And the\n*simulator* needs no change either: Model A's latent is $u^*_{it}$, so\ngenerating Model A data with per-respondent cut points $c + z_i$ produces\nexactly $u^*_{it}$ graded against $c + z_i$, which is the persistent model.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: setup\nset.seed(1)\noptions(digits = 5)\n```\n:::\n\n\n## 1. Machinery\n\nDesigns, the panel simulator, and a sampler that carries a respondent-level\ncut-point shift. This notebook needs neither the heterogeneous-cut mode nor the\nchoice-only mode, so the sampler below is the common-cut sampler plus one\nscalar latent per respondent.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden  code-fold=\"true\" code-summary=\"Designs, panel simulation, and the sampler with a persistent shift\"}\n#| label: machinery\n#| code-fold: true\n#| code-summary: \"Designs, panel simulation, and the sampler with a persistent shift\"\nrgumbel <- function(n) -log(-log(runif(n)))\nrow_max <- function(M) do.call(pmax, as.data.frame(M))\n\n# ---- designs (R/lib/dgp.R) --------------------------------------------------\nmake_design <- function(n_tasks, J, seed, intercept = FALSE) {\n  set.seed(seed)\n  n_rows <- n_tasks * J\n  a <- sample(1:3, n_rows, replace = TRUE)\n  b <- sample(1:3, n_rows, replace = TRUE)\n  price <- runif(n_rows, 0.5, 2.5)\n  X <- cbind(a2 = as.numeric(a == 2), a3 = as.numeric(a == 3),\n             b2 = as.numeric(b == 2), b3 = as.numeric(b == 3), price = price)\n  if (intercept) X <- cbind(X, const = 1)\n  list(X = X, n_tasks = n_tasks, J = J, P = ncol(X))\n}\nmake_panel_design <- function(N, T_tasks, J, seed) {\n  des <- make_design(N * T_tasks, J, seed = seed)\n  des$N <- N; des$T_tasks <- T_tasks\n  des$resp <- rep(seq_len(N), each = T_tasks)\n  des$resp_row <- rep(des$resp, each = J)\n  des\n}\n\n# ---- cut-point parameterization and link (R/lib/likelihood.R) --------------\npar_to_cut <- function(par, P, W) {\n  if (W == 2) return(par[P + 1])\n  par[P + 1] + c(0, cumsum(exp(par[(P + 2):(P + W - 1)])))\n}\ncut_to_par <- function(cut) if (length(cut) == 1) cut else c(cut[1], log(diff(cut)))\nord_prob_z <- function(lo, hi, model) {\n  if (model == \"B\") {\n    plogis(hi) * plogis(-lo) * (-expm1(lo - hi))\n  } else {\n    ea <- exp(-lo); eb <- exp(-hi)\n    p <- exp(-eb) * (-expm1(-(ea - eb)))\n    p[!is.finite(eb)] <- 0\n    p\n  }\n}\n\n# ---- panel simulation (R/hierarchical/dgp_panel.R) -------------------------\ndraw_betas <- function(N, beta_bar, Sigma, seed) {\n  set.seed(seed)\n  sweep(matrix(rnorm(N * length(beta_bar)), N, length(beta_bar)) %*% chol(Sigma),\n        2, beta_bar, \"+\")\n}\nsimulate_dual_hb <- function(design, Bmat, cut, model = c(\"A\", \"B\"), seed) {\n  model <- match.arg(model); set.seed(seed)\n  n <- design$n_tasks; J <- design$J; N <- design$N\n  cutmat <- if (is.matrix(cut)) cut else matrix(cut, N, length(cut), byrow = TRUE)\n  W <- ncol(cutmat) + 1L\n  Bx <- Bmat[design$resp_row, , drop = FALSE]\n  V <- matrix(rowSums(design$X * Bx), nrow = n, ncol = J, byrow = TRUE)\n  u <- V + matrix(rgumbel(n * J), n, J)\n  jstar <- max.col(u, ties.method = \"first\")\n  ustar <- u[cbind(seq_len(n), jstar)]\n  latent <- if (model == \"A\") ustar else ustar - rgumbel(n)\n  y <- 1L + rowSums(latent >= cutmat[design$resp, , drop = FALSE])\n  list(design = design, resp = design$resp, resp_row = design$resp_row,\n       N = N, jstar = jstar, y = as.integer(y), W = W, model = model,\n       Bmat_true = Bmat, cut_true = cut)\n}\nsplit_holdout <- function(dat, n_holdout) {\n  des <- dat$design; Tt <- des$T_tasks\n  tt <- rep(seq_len(Tt), times = des$N)\n  keep <- tt <= (Tt - n_holdout)\n  sub <- function(k) {\n    rows <- rep(k, each = des$J)\n    d <- list(X = des$X[rows, , drop = FALSE], n_tasks = sum(k), J = des$J,\n              P = des$P, N = des$N, T_tasks = if (all(k == keep)) Tt - n_holdout else n_holdout,\n              resp = des$resp[k], resp_row = des$resp_row[rows])\n    list(design = d, resp = d$resp, resp_row = d$resp_row, N = des$N,\n         jstar = dat$jstar[k], y = dat$y[k], W = dat$W, model = dat$model,\n         Bmat_true = dat$Bmat_true, cut_true = dat$cut_true)\n  }\n  list(est = sub(keep), holdout = sub(!keep))\n}\n\n# ---- the sampler -----------------------------------------------------------\n# N-vector of per-respondent joint log-likelihoods.\nresp_loglik_all <- function(dat, Bmat, cutmat) {\n  des <- dat$design; n <- des$n_tasks; J <- des$J\n  Bx <- Bmat[dat$resp_row, , drop = FALSE]\n  V <- matrix(rowSums(des$X * Bx), nrow = n, ncol = J, byrow = TRUE)\n  m <- row_max(V); logS <- m + log(rowSums(exp(V - m)))\n  ll <- V[cbind(seq_len(n), dat$jstar)] - logS\n  cut_aug <- cbind(-Inf, cutmat, Inf)\n  lo <- cut_aug[cbind(dat$resp, dat$y)] - logS\n  hi <- cut_aug[cbind(dat$resp, dat$y + 1L)] - logS\n  ll <- ll + log(pmax(ord_prob_z(lo, hi, dat$model), 1e-312))\n  as.numeric(rowsum(ll, dat$resp, reorder = TRUE))\n}\ndefault_hb_priors <- function(P) list(\n  phibar0 = rep(0, P), A = 1/100, nu = P + 3, V0 = (P + 3) * diag(P),\n  zeta_prec = 1/100, a_z = 2, b_z = 2)\ndraw_phibar <- function(B, Sigma, priors) {\n  N <- nrow(B); Sinv <- chol2inv(chol(Sigma))\n  Vb <- chol2inv(chol(N * Sinv + priors$A * diag(ncol(B))))\n  m <- Vb %*% (Sinv %*% (N * colMeans(B)) + priors$A * priors$phibar0)\n  as.numeric(m + t(chol(Vb)) %*% rnorm(ncol(B)))\n}\ndraw_sigma <- function(B, betabar, priors) {\n  Vn <- priors$V0 + crossprod(sweep(B, 2, betabar))\n  chol2inv(chol(rWishart(1, priors$nu + nrow(B), chol2inv(chol(Vn)))[, , 1]))\n}\n\nEULER <- -digamma(1)   # 0.57722\n\n# persist = FALSE -> ordinary common-cut sampler.\n# persist = TRUE  -> one scalar shift z_i per respondent, cut points c + z_i.\n#   persist_prior \"normal\": z_i ~ N(0, s2z), s2z estimated  (the TEST)\n#   persist_prior \"gumbel\": z_i ~ Gumbel(0,1) - EULER, fixed (the THEORY)\nfit_hb <- function(dat, mcmc = list(R = 15000, burn = 6000, thin = 10),\n                   persist = FALSE, persist_prior = c(\"normal\", \"gumbel\"),\n                   priors = NULL, seed = NULL, verbose = TRUE) {\n  persist_prior <- match.arg(persist_prior)\n  if (!is.null(seed)) set.seed(seed)\n  des <- dat$design; N <- dat$N; P <- des$P; W <- dat$W\n  if (is.null(priors)) priors <- default_hb_priors(P)\n  R_iter <- mcmc$R; burn <- mcmc$burn; thin <- mcmc$thin\n  nkeep <- floor((R_iter - burn) / thin)\n\n  lpz <- function(z) if (!persist) 0 else if (persist_prior == \"gumbel\") {\n    g <- z + EULER; -g - exp(-g)\n  } else -0.5 * z^2 / s2z\n\n  B <- matrix(0, N, P); z <- numeric(N)\n  freq <- tabulate(dat$y, nbins = W)\n  cumq <- pmin(pmax(cumsum(freq)[1:(W - 1)] / sum(freq), 1e-4), 1 - 1e-4)\n  ginv <- if (dat$model == \"B\") qlogis else function(q) -log(-log(q))\n  cut0 <- log(des$J) + ginv(cumq)\n  if (W > 2) for (k in 2:(W - 1)) cut0[k] <- max(cut0[k], cut0[k - 1] + 1e-3)\n  zeta <- cut_to_par(cut0)\n  betabar <- rep(0, P); Sigma <- diag(P); s2z <- 1\n\n  cutrow <- function(zz, zv) matrix(par_to_cut(zz, 0, W), N, W - 1, byrow = TRUE) + zv\n  cur_cutmat <- cutrow(zeta, z)\n  cur_ll <- resp_loglik_all(dat, B, cur_cutmat)\n\n  s_phi <- rep(2.93 / sqrt(P + persist), N); acc_phi <- rep(0, N)\n  s_zeta <- 0.05; acc_zeta <- 0; window <- 100\n\n  keep_betabar <- matrix(NA_real_, nkeep, P)\n  keep_Sigma <- array(NA_real_, c(nkeep, P, P))\n  keep_cut <- matrix(NA_real_, nkeep, W - 1)\n  keep_s2z <- numeric(nkeep)\n  keep_B <- array(NA_real_, c(nkeep, N, P))\n  keep_z <- matrix(NA_real_, nkeep, N)\n  ki <- 0\n\n  for (it in seq_len(R_iter)) {\n    # (1) respondent block: (beta_i, z_i) jointly by RW-MH\n    Bp <- B + (matrix(rnorm(N * P), N, P) %*% chol(Sigma)) * s_phi\n    zp <- if (persist) z + rnorm(N, sd = s_phi * sqrt(s2z)) else z\n    cutp <- if (persist) cutrow(zeta, zp) else cur_cutmat\n    prop_ll <- resp_loglik_all(dat, Bp, cutp)\n    Sinv <- chol2inv(chol(Sigma))\n    dc <- sweep(B, 2, betabar); dp <- sweep(Bp, 2, betabar)\n    qc <- rowSums((dc %*% Sinv) * dc); qp <- rowSums((dp %*% Sinv) * dp)\n    la <- (prop_ll - 0.5 * qp + lpz(zp)) - (cur_ll - 0.5 * qc + lpz(z))\n    acc <- log(runif(N)) < la\n    B[acc, ] <- Bp[acc, ]; cur_ll[acc] <- prop_ll[acc]\n    if (persist && any(acc)) { z[acc] <- zp[acc]; cur_cutmat[acc, ] <- cutp[acc, , drop = FALSE] }\n    acc_phi <- acc_phi + acc\n\n    # (2) common-cut block\n    zeta_prop <- zeta + rnorm(W - 1, sd = s_zeta)\n    cut_prop <- cutrow(zeta_prop, z)\n    ll_prop <- resp_loglik_all(dat, B, cut_prop)\n    lp <- (sum(ll_prop) - 0.5 * priors$zeta_prec * sum(zeta_prop^2)) -\n          (sum(cur_ll) - 0.5 * priors$zeta_prec * sum(zeta^2))\n    if (log(runif(1)) < lp) {\n      zeta <- zeta_prop; cur_cutmat <- cut_prop; cur_ll <- ll_prop\n      acc_zeta <- acc_zeta + 1\n    }\n\n    # (3) hyperparameters\n    betabar <- draw_phibar(B, Sigma, priors)\n    Sigma <- draw_sigma(B, betabar, priors)\n    if (persist && persist_prior == \"normal\")\n      s2z <- 1 / rgamma(1, priors$a_z + N / 2, priors$b_z + sum(z^2) / 2)\n\n    if (it <= burn && it %% window == 0) {\n      s_phi <- pmin(pmax(s_phi * exp(1.5 * (acc_phi / window - 0.23)), 0.01), 10)\n      acc_phi <- rep(0, N)\n      s_zeta <- min(max(s_zeta * exp(1.5 * (acc_zeta / window - 0.30)), 1e-3), 2)\n      acc_zeta <- 0\n    }\n    if (it == burn) { acc_phi <- rep(0, N); acc_zeta <- 0 }\n    if (it > burn && (it - burn) %% thin == 0) {\n      ki <- ki + 1\n      keep_betabar[ki, ] <- betabar; keep_Sigma[ki, , ] <- Sigma\n      keep_cut[ki, ] <- par_to_cut(zeta, 0, W); keep_s2z[ki] <- s2z\n      keep_B[ki, , ] <- B; keep_z[ki, ] <- z\n    }\n  }\n  list(draws = list(betabar = keep_betabar, Sigma = keep_Sigma, cut = keep_cut,\n                    s2z = keep_s2z, B = keep_B, z = keep_z),\n       settings = list(P = P, W = W, N = N, persist = persist,\n                       persist_prior = persist_prior, model = dat$model, mcmc = mcmc))\n}\nhb_beta_i <- function(fit) apply(fit$draws$B, c(2, 3), mean)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: config\nN <- 300; T_EST <- 12; T_HOLD <- 2; J <- 4; W <- 5\nbeta_bar   <- c(a2 = 0.8, a3 = -0.5, b2 = 0.4, b3 = 1.0, price = -0.9)\nSigma_true <- diag(c(0.6, 0.6, 0.6, 0.6, 0.3))\ncut_true   <- c(-1.0, 0.2, 1.2, 2.2)\nP <- length(beta_bar)\nKBUY <- 4                        # \"purchase\" = top-2-box, as elsewhere\nREPS <- 6\nITER <- 15000\nMCMC <- list(R = ITER, burn = floor(ITER * 0.4), thin = 10)\nVAR_GUMBEL <- pi^2 / 6           # 1.6449: what the theory predicts\n\n# Persistent data: Model A latent (u*) graded against per-respondent cuts c+z.\ngen_persistent <- function(seed, zvec) {\n  des <- make_panel_design(N, T_EST + T_HOLD, J, seed = seed)\n  B <- draw_betas(N, beta_bar, Sigma_true, seed = seed + 1)\n  cutmat <- outer(zvec, cut_true, \"+\")\n  split_holdout(simulate_dual_hb(des, B, cutmat, model = \"A\", seed = seed + 2), T_HOLD)\n}\n# Transient data: Model B, fresh outside shock every task.\ngen_transient <- function(seed) {\n  des <- make_panel_design(N, T_EST + T_HOLD, J, seed = seed)\n  B <- draw_betas(N, beta_bar, Sigma_true, seed = seed + 1)\n  split_holdout(simulate_dual_hb(des, B, cut_true, model = \"B\", seed = seed + 2), T_HOLD)\n}\nres <- list()\n```\n:::\n\n\n## 2. The two are marginally identical\n\nFirst the claim that makes this subtle. A Gumbel drawn once per respondent and\na Gumbel drawn once per task produce *the same* per-task answer distribution,\nbecause in both cases the latent $u^*_{it} - (\\text{Gumbel})$ is\n$\\text{Logistic}(\\overline\\mu_{it}, 1)$. The draws differ only in how they are\nshared across a respondent's tasks.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: marginal-equivalence\nset.seed(20)\nzc <- rgumbel(N) - EULER                           # persistent, centred\nsp_p <- gen_persistent(30000, zc)\nsp_t <- gen_transient(30000)\n\ntab <- rbind(\n  persistent = tabulate(sp_p$est$y, W) / length(sp_p$est$y),\n  transient  = tabulate(sp_t$est$y, W) / length(sp_t$est$y))\nknitr::kable(round(tab, 4), caption = \"Marginal distribution of the ordinal answer\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Marginal distribution of the ordinal answer\n\n|           |       |       |       |       |       |\n|:----------|------:|------:|------:|------:|------:|\n|persistent | 0.1228| 0.1369| 0.1600| 0.1758| 0.4044|\n|transient  | 0.1469| 0.1769| 0.1989| 0.1944| 0.2828|\n\n\n:::\n:::\n\n\nNow the same two datasets, looked at as panels. For each respondent take the\ncorrelation of her ordinal answers across task pairs.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: dependence\nwithin_cor <- function(dat) {\n  Y <- matrix(dat$y, nrow = dat$N, byrow = TRUE)\n  # remove the task-level mean so design variation is not mistaken for dependence\n  Yc <- sweep(Y, 2, colMeans(Y))\n  cm <- cor(Yc); mean(cm[upper.tri(cm)])\n}\nres$dependence <- c(persistent = within_cor(sp_p$est),\n                    transient  = within_cor(sp_t$est))\nround(res$dependence, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npersistent  transient \n    0.5771     0.1632 \n```\n\n\n:::\n:::\n\n\nIndistinguishable in the margin, clearly different in the panel. **A\ncross-section cannot tell these models apart at all**; the information lives\nentirely in the repeated measurements, which is the one thing conjoint data\nalways has.\n\nNote that the transient figure is not zero, and should not be. Preference\nheterogeneity already correlates a respondent's answers: someone with a large\n$\\beta_i$ has a high $\\overline\\mu_{it}$ on all of her tasks and answers high\nthroughout. The persistent shock adds dependence *on top of* that, and it is the\nincrement, not the level, that identifies it.\n\n## 3. Does the sampler recover the shift?\n\nBefore testing the theory's number we need to know the estimator works. Simulate\nwith $z_i \\sim \\mathcal{N}(0, \\sigma_z^2)$ at three values of $\\sigma_z^2$ and\nfit the free (normal-prior) persistent model.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: recovery\nsig_grid <- c(0.0, 0.8, 1.6449)\nrec <- expand.grid(rep = seq_len(REPS), s2 = sig_grid)\nrec$s2_hat <- NA_real_; rec$lo <- NA_real_; rec$hi <- NA_real_\nfor (k in seq_len(nrow(rec))) {\n  sd_k <- sqrt(rec$s2[k]); sk <- 40000 + 100 * k\n  set.seed(sk)\n  zv <- if (sd_k == 0) numeric(N) else rnorm(N, sd = sd_k)\n  sp <- gen_persistent(sk, zv)\n  f <- fit_hb(sp$est, mcmc = MCMC, persist = TRUE, seed = sk + 7, verbose = FALSE)\n  q <- quantile(f$draws$s2z, c(0.025, 0.975))\n  rec[k, c(\"s2_hat\", \"lo\", \"hi\")] <- c(mean(f$draws$s2z), q[1], q[2])\n}\nres$recovery <- rec\nagg <- do.call(rbind, lapply(split(rec, rec$s2), function(d) data.frame(\n  s2_true = d$s2[1], s2_hat = mean(d$s2_hat),\n  mc_se = sd(d$s2_hat) / sqrt(nrow(d)),\n  excludes_gumbel = mean(d$hi < VAR_GUMBEL | d$lo > VAR_GUMBEL))))\nknitr::kable(agg, digits = 4, row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n| s2_true| s2_hat|  mc_se| excludes_gumbel|\n|-------:|------:|------:|---------------:|\n|  0.0000| 0.2213| 0.0065|               1|\n|  0.8000| 0.8513| 0.0438|               1|\n|  1.6449| 1.6418| 0.0465|               0|\n\n\n:::\n:::\n\n\nTwo things to read here, and one trap to avoid.\n\nThe estimator tracks the truth where there is something to track. A\nrespondent-level shift and genuine preference heterogeneity are separable\nbecause they leave different fingerprints: $z_i$ moves every one of respondent\n$i$'s tasks by the same amount, while $\\beta_i$ variation moves them by\ntask-dependent amounts.\n\nThe trap is the $\\sigma_z^2 = 0$ row. It does **not** return zero, and no amount\nof data will make it. Each $z_i$ is estimated from only $T$ ordinal answers, so\nthe $z_i$ carry estimation noise even when the truth is zero, and $\\sigma_z^2$\nabsorbs that noise as variance. The inverse-gamma posterior also places no\ndensity at the boundary, so an interval covering zero is unavailable even in\nprinciple. What the null row reports instead is this design's **detection\nfloor**: the smallest respondent-level shift that $T$ tasks can resolve. Read it\nas a floor, never as an estimate of zero.\n\nSo the column that carries the weight is the last one. Does the interval exclude\nthe $\\pi^2/6$ the theory predicts? At the null it does, decisively, and that is\nthe property the test in the next section needs.\n\n## 4. The theory's number\n\nNow the test the model section needs. Generate data from the *actual* behavioral\nstory — a persistent $\\text{Gumbel}(0,1)$ outside shock — and estimate\n$\\sigma_z^2$ freely. Theory says $\\pi^2/6 = 1.645$.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: theory-test\nth <- data.frame(rep = seq_len(REPS), s2_hat = NA_real_, lo = NA_real_, hi = NA_real_)\npanels <- vector(\"list\", REPS)\nfor (r in seq_len(REPS)) {\n  sk <- 50000 + 100 * r\n  set.seed(sk)\n  zv <- rgumbel(N) - EULER\n  panels[[r]] <- gen_persistent(sk, zv)\n  f <- fit_hb(panels[[r]]$est, mcmc = MCMC, persist = TRUE, seed = sk + 7, verbose = FALSE)\n  q <- quantile(f$draws$s2z, c(0.025, 0.975))\n  th[r, 2:4] <- c(mean(f$draws$s2z), q[1], q[2])\n}\nres$theory_test <- list(tab = th, target = VAR_GUMBEL,\n                        mean = mean(th$s2_hat),\n                        se = sd(th$s2_hat) / sqrt(REPS),\n                        cover = mean(th$lo <= VAR_GUMBEL & VAR_GUMBEL <= th$hi))\nknitr::kable(data.frame(\n  target_pi2_6 = VAR_GUMBEL, mean_estimate = res$theory_test$mean,\n  mc_se = res$theory_test$se, coverage_of_target = res$theory_test$cover),\n  digits = 4, row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n| target_pi2_6| mean_estimate|  mc_se| coverage_of_target|\n|------------:|-------------:|------:|------------------:|\n|       1.6449|        1.8445| 0.0837|             0.8333|\n\n\n:::\n:::\n\n\nThis is an overidentification test of the same kind as $\\lambda = 1$ and\n$\\delta = 0$: the behavioral story predicts a specific number that the data are\nfree to contradict.\n\nRead the estimate against the previous section's top row, though. There, with a\ngenuinely *normal* shift of variance $1.6449$, the estimator returned $1.64$. Here,\nwith a genuinely *Gumbel* shift of the same variance, it returns about $1.84$. The\ngap is not sampling error; it is roughly two and a half Monte Carlo standard errors.\nThe population model fits a symmetric normal to a right-skewed Gumbel, and the\nfitted variance absorbs the skew.\n\nSo the test is biased against its own null: an estimate modestly above $\\pi^2/6$ is\nwhat the *correct* model produces, not evidence against it. Treat $\\pi^2/6$ as a\nlower reference point rather than a target to be matched, or impose the Gumbel\ndirectly (next section) and give up testing it.\n\n## 5. What ignoring it costs\n\nFit the ordinary transient model (Model B, common cuts, no $z$) to the\npersistent data from the previous section, and compare against the persistent\nfit on the same panels.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: cost\ncmp <- matrix(NA_real_, REPS, 4, dimnames = list(NULL,\n  c(\"rmse_beta_transient\", \"rmse_beta_persistent\",\n    \"hit_transient\", \"hit_persistent\")))\nhit_rate <- function(fit, sp) {\n  d <- sp$holdout$design\n  Bx <- hb_beta_i(fit)[d$resp_row, , drop = FALSE]\n  V <- matrix(rowSums(d$X * Bx), ncol = d$J, byrow = TRUE)\n  mean(max.col(V, ties.method = \"first\") == sp$holdout$jstar)\n}\nfor (r in seq_len(REPS)) {\n  sp <- panels[[r]]; sk <- 60000 + 100 * r\n  f_tr <- fit_hb(sp$est, mcmc = MCMC, persist = FALSE, seed = sk, verbose = FALSE)\n  f_pe <- fit_hb(sp$est, mcmc = MCMC, persist = TRUE,  seed = sk + 1, verbose = FALSE)\n  cmp[r, ] <- c(sqrt(mean((hb_beta_i(f_tr) - sp$est$Bmat_true)^2)),\n                sqrt(mean((hb_beta_i(f_pe) - sp$est$Bmat_true)^2)),\n                hit_rate(f_tr, sp), hit_rate(f_pe, sp))\n}\nres$cost <- list(metrics = cmp, mean = colMeans(cmp),\n                 se = apply(cmp, 2, sd) / sqrt(REPS))\nknitr::kable(rbind(mean = res$cost$mean, mc_se = res$cost$se), digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|      | rmse_beta_transient| rmse_beta_persistent| hit_transient| hit_persistent|\n|:-----|-------------------:|--------------------:|-------------:|--------------:|\n|mean  |              0.6062|               0.5242|        0.4958|         0.5044|\n|mc_se |              0.0094|               0.0056|        0.0059|         0.0112|\n\n\n:::\n:::\n\n\nThe forced-choice side is untouched, as it must be: the persistent shock enters\nonly the second response, so hit rates are the same either way. Whatever\ndifference appears is in the individual preference estimates, where the\ntransient model has to explain a respondent-constant shift using parameters that\nare not respondent-constant.\n\n## 6. Imposing the theory instead of testing it\n\nThe free version spends one parameter. The theory says we need not: fix\n$z_i \\sim \\text{Gumbel}(0,1)$ and the model costs nothing at all. Fit both to\nthe same panels and compare what they say about the population.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: imposed\nimp <- matrix(NA_real_, REPS, 2, dimnames = list(NULL, c(\"rmse_free\", \"rmse_imposed\")))\nfor (r in seq_len(REPS)) {\n  sp <- panels[[r]]; sk <- 70000 + 100 * r\n  f_free <- fit_hb(sp$est, mcmc = MCMC, persist = TRUE,\n                   persist_prior = \"normal\", seed = sk, verbose = FALSE)\n  f_imp  <- fit_hb(sp$est, mcmc = MCMC, persist = TRUE,\n                   persist_prior = \"gumbel\", seed = sk + 1, verbose = FALSE)\n  imp[r, ] <- c(sqrt(mean((colMeans(f_free$draws$betabar) - beta_bar)^2)),\n                sqrt(mean((colMeans(f_imp$draws$betabar)  - beta_bar)^2)))\n}\nres$imposed <- list(metrics = imp, mean = colMeans(imp),\n                    se = apply(imp, 2, sd) / sqrt(REPS))\nknitr::kable(rbind(mean = res$imposed$mean, mc_se = res$imposed$se), digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|      | rmse_free| rmse_imposed|\n|:-----|---------:|------------:|\n|mean  |    0.0722|       0.0709|\n|mc_se |    0.0056|       0.0058|\n\n\n:::\n:::\n\n\nImposing the Gumbel buys whatever the restriction is worth when it is true. The\nhonest sequence for an application is to fit the free version, check\n$\\sigma_z^2$ against $1.645$, and impose only if the data do not reject it.\n\n## 7. What this adds up to\n\n- The persistent and transient outside options are **marginally\n  indistinguishable**. Any argument between them is a panel argument.\n- The persistent version is **location-only cut-point heterogeneity** with the\n  location's distribution fixed by theory rather than estimated — which is why\n  it costs one scalar latent per respondent and no new parameters.\n- It is **testable**: $\\sigma_z^2 = \\pi^2/6$ is a prediction, not a convention.\n- It gives the respondent-specific scale use of the heterogeneous-cut extension\n  a **structural reason** rather than a descriptive one. A respondent who seems\n  to use the top of the scale freely may simply have a weak outside option.\n\n## 8. Results written\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: write\nPROJ <- if (file.exists(\"_quarto.yml\")) \".\" else \"..\"\nOUT  <- file.path(PROJ, \"R\", \"output\")\ndir.create(OUT, showWarnings = FALSE, recursive = TRUE)\nres$config <- list(N = N, T_EST = T_EST, T_HOLD = T_HOLD, J = J, W = W,\n                   beta_bar = beta_bar, Sigma_true = Sigma_true,\n                   cut_true = cut_true, REPS = REPS, MCMC = MCMC,\n                   KBUY = KBUY, var_gumbel = VAR_GUMBEL)\nsaveRDS(res, file.path(OUT, \"persistent_outside.rds\"))\ncat(\"wrote\", file.path(OUT, \"persistent_outside.rds\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwrote ./R/output/persistent_outside.rds \n```\n\n\n:::\n:::\n\n\n## 9. Related material\n\n- Notebook 03 establishes that the hierarchical sampler works at all; this one\n  extends it by one latent per respondent.\n- Notebook 06, section 3, studies *free* cut-point heterogeneity. The model here\n  is its restricted, theory-pinned cousin: location only, variance fixed.\n- The model section derives why the persistent and transient stories share a\n  link and differ only in the panel.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}